/* ═══════════════════════════════════════════════════════════════
   FOOD / NUTRITION TRACKER DATA
   Target user: Priya — T2DM · HTN · Dyslipidaemia
   All nutrient values are per single serving unless noted.
   ═══════════════════════════════════════════════════════════════ */

/* ───────────────────────────────────────────────────────────────
   1. FOOD_USER — user profile
   ─────────────────────────────────────────────────────────────── */
const FOOD_USER = {
  name: 'Priya',
  age: 38,
  wt: 64,
  ht: 162,
  conditions: ['T2DM', 'HTN', 'Dyslipidaemia'],
  meds: ['Metformin', 'Amlodipine', 'Atorvastatin'],
};

/* ───────────────────────────────────────────────────────────────
   2. NUTRITION_GOALS — daily clinical targets
   ─────────────────────────────────────────────────────────────── */
const NUTRITION_GOALS = {
  cal: 1650,
  pro: 65,
  carb: 185,
  fat: 55,
  fib: 28,
  sug: 30,
  sod: 1500,
  pot: 3500,
  cal_m: 1000,
  iron: 18,
  mag: 320,
  vitC: 75,
  vitD: 600,
  vitB12: 2.4,
  folate: 400,
  vitA: 700,
  vitK: 90,
  vitE: 15,
  vitB6: 1.3,
  zinc: 8,
  selenium: 55,
  chromium: 25,
  omega3: 1100,
};

/* ───────────────────────────────────────────────────────────────
   3. FOOD_DB — 34 food items keyed by id
      Nutrient keys:
        n    = name          cat  = category       ico = emoji
        w    = weight (g)    u    = unit name
        cal  = kcal          pro  = protein g       carb = carbs g
        fat  = fat g         fib  = fibre g         sug  = sugar g
        sod  = sodium mg     pot  = potassium mg    cal_m = calcium mg
        iron = mg            mag  = magnesium mg    vitC = mg
        vitD = IU            vitB12 = µg            folate = µg DFE
        vitA = µg RAE
   ─────────────────────────────────────────────────────────────── */
const FOOD_DB = {

  /* ── South Indian (6) ──────────────────────────────────────── */
  idli: {
    n: 'Idli',
    cat: 'South Indian',
    ico: '🫓',
    w: 40,
    u: 'piece',
    cal: 58,
    pro: 2.0,
    carb: 12.0,
    fat: 0.4,
    fib: 0.5,
    sug: 0.3,
    sod: 140,
    pot: 35,
    cal_m: 8,
    iron: 0.4,
    mag: 7,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 8,
    vitA: 1,
  },
  dosa: {
    n: 'Dosa (plain)',
    cat: 'South Indian',
    ico: '🥞',
    w: 80,
    u: 'piece',
    cal: 120,
    pro: 3.2,
    carb: 18.0,
    fat: 3.8,
    fib: 0.8,
    sug: 0.5,
    sod: 180,
    pot: 60,
    cal_m: 12,
    iron: 0.7,
    mag: 14,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 12,
    vitA: 2,
  },
  sambar: {
    n: 'Sambar',
    cat: 'South Indian',
    ico: '🍲',
    w: 150,
    u: 'katori',
    cal: 110,
    pro: 5.5,
    carb: 15.0,
    fat: 3.2,
    fib: 3.0,
    sug: 2.5,
    sod: 420,
    pot: 280,
    cal_m: 40,
    iron: 1.6,
    mag: 30,
    vitC: 8,
    vitD: 0,
    vitB12: 0,
    folate: 45,
    vitA: 18,
  },
  upma: {
    n: 'Upma',
    cat: 'South Indian',
    ico: '🍚',
    w: 180,
    u: 'katori',
    cal: 210,
    pro: 5.0,
    carb: 30.0,
    fat: 7.5,
    fib: 2.2,
    sug: 1.0,
    sod: 350,
    pot: 90,
    cal_m: 22,
    iron: 1.2,
    mag: 18,
    vitC: 2,
    vitD: 0,
    vitB12: 0,
    folate: 15,
    vitA: 5,
  },
  rasam: {
    n: 'Rasam',
    cat: 'South Indian',
    ico: '🥣',
    w: 150,
    u: 'katori',
    cal: 42,
    pro: 1.8,
    carb: 6.5,
    fat: 1.2,
    fib: 0.8,
    sug: 1.5,
    sod: 380,
    pot: 180,
    cal_m: 18,
    iron: 0.8,
    mag: 12,
    vitC: 12,
    vitD: 0,
    vitB12: 0,
    folate: 10,
    vitA: 10,
  },
  coconut_chutney: {
    n: 'Coconut Chutney',
    cat: 'South Indian',
    ico: '🥥',
    w: 30,
    u: 'tbsp',
    cal: 50,
    pro: 0.8,
    carb: 2.5,
    fat: 4.2,
    fib: 0.9,
    sug: 1.2,
    sod: 60,
    pot: 45,
    cal_m: 5,
    iron: 0.3,
    mag: 6,
    vitC: 1,
    vitD: 0,
    vitB12: 0,
    folate: 3,
    vitA: 0,
  },

  /* ── North Indian (4) ──────────────────────────────────────── */
  roti: {
    n: 'Roti (whole wheat)',
    cat: 'North Indian',
    ico: '🫓',
    w: 35,
    u: 'piece',
    cal: 85,
    pro: 3.0,
    carb: 15.0,
    fat: 1.5,
    fib: 2.0,
    sug: 0.3,
    sod: 120,
    pot: 55,
    cal_m: 12,
    iron: 1.0,
    mag: 20,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 10,
    vitA: 0,
  },
  dal_tadka: {
    n: 'Dal Tadka',
    cat: 'North Indian',
    ico: '🍛',
    w: 150,
    u: 'katori',
    cal: 140,
    pro: 7.5,
    carb: 17.0,
    fat: 4.5,
    fib: 4.0,
    sug: 1.8,
    sod: 380,
    pot: 310,
    cal_m: 30,
    iron: 2.2,
    mag: 35,
    vitC: 3,
    vitD: 0,
    vitB12: 0,
    folate: 60,
    vitA: 8,
  },
  paneer_curry: {
    n: 'Paneer Curry',
    cat: 'North Indian',
    ico: '🧀',
    w: 150,
    u: 'katori',
    cal: 230,
    pro: 12.0,
    carb: 8.0,
    fat: 17.0,
    fib: 1.2,
    sug: 2.5,
    sod: 420,
    pot: 140,
    cal_m: 280,
    iron: 1.0,
    mag: 18,
    vitC: 4,
    vitD: 10,
    vitB12: 0.4,
    folate: 20,
    vitA: 85,
  },
  biryani: {
    n: 'Veg Biryani',
    cat: 'North Indian',
    ico: '🍚',
    w: 250,
    u: 'serving',
    cal: 350,
    pro: 8.0,
    carb: 52.0,
    fat: 12.0,
    fib: 2.5,
    sug: 2.0,
    sod: 620,
    pot: 180,
    cal_m: 35,
    iron: 1.8,
    mag: 25,
    vitC: 5,
    vitD: 0,
    vitB12: 0,
    folate: 22,
    vitA: 30,
  },

  /* ── Protein (4) ───────────────────────────────────────────── */
  chicken_curry: {
    n: 'Chicken Curry',
    cat: 'Protein',
    ico: '🍗',
    w: 150,
    u: 'katori',
    cal: 220,
    pro: 22.0,
    carb: 5.0,
    fat: 12.5,
    fib: 0.8,
    sug: 1.5,
    sod: 480,
    pot: 290,
    cal_m: 22,
    iron: 1.5,
    mag: 24,
    vitC: 3,
    vitD: 5,
    vitB12: 0.8,
    folate: 12,
    vitA: 35,
  },
  egg_whole: {
    n: 'Boiled Egg',
    cat: 'Protein',
    ico: '🥚',
    w: 50,
    u: 'piece',
    cal: 78,
    pro: 6.3,
    carb: 0.6,
    fat: 5.3,
    fib: 0,
    sug: 0.6,
    sod: 62,
    pot: 63,
    cal_m: 25,
    iron: 0.9,
    mag: 5,
    vitC: 0,
    vitD: 44,
    vitB12: 0.6,
    folate: 22,
    vitA: 75,
  },
  fish_curry: {
    n: 'Fish Curry',
    cat: 'Protein',
    ico: '🐟',
    w: 150,
    u: 'katori',
    cal: 190,
    pro: 20.0,
    carb: 4.5,
    fat: 10.0,
    fib: 0.5,
    sug: 1.2,
    sod: 440,
    pot: 350,
    cal_m: 30,
    iron: 1.2,
    mag: 32,
    vitC: 4,
    vitD: 120,
    vitB12: 2.5,
    folate: 15,
    vitA: 20,
  },
  dal_makhani: {
    n: 'Dal Makhani',
    cat: 'Protein',
    ico: '🫘',
    w: 150,
    u: 'katori',
    cal: 195,
    pro: 8.0,
    carb: 20.0,
    fat: 9.5,
    fib: 4.5,
    sug: 2.0,
    sod: 450,
    pot: 340,
    cal_m: 42,
    iron: 2.5,
    mag: 38,
    vitC: 2,
    vitD: 0,
    vitB12: 0,
    folate: 65,
    vitA: 12,
  },

  /* ── Vegetables (4) ────────────────────────────────────────── */
  spinach: {
    n: 'Spinach (cooked)',
    cat: 'Vegetables',
    ico: '🥬',
    w: 100,
    u: 'katori',
    cal: 23,
    pro: 2.9,
    carb: 3.6,
    fat: 0.4,
    fib: 2.4,
    sug: 0.4,
    sod: 70,
    pot: 466,
    cal_m: 136,
    iron: 3.6,
    mag: 87,
    vitC: 10,
    vitD: 0,
    vitB12: 0,
    folate: 146,
    vitA: 524,
  },
  bitter_gourd: {
    n: 'Bitter Gourd (cooked)',
    cat: 'Vegetables',
    ico: '🥒',
    w: 100,
    u: 'katori',
    cal: 28,
    pro: 1.5,
    carb: 4.8,
    fat: 0.3,
    fib: 2.0,
    sug: 1.2,
    sod: 6,
    pot: 296,
    cal_m: 9,
    iron: 0.6,
    mag: 16,
    vitC: 33,
    vitD: 0,
    vitB12: 0,
    folate: 51,
    vitA: 6,
  },
  broccoli: {
    n: 'Broccoli (steamed)',
    cat: 'Vegetables',
    ico: '🥦',
    w: 100,
    u: 'katori',
    cal: 35,
    pro: 2.4,
    carb: 7.2,
    fat: 0.4,
    fib: 3.3,
    sug: 1.4,
    sod: 40,
    pot: 293,
    cal_m: 40,
    iron: 0.7,
    mag: 21,
    vitC: 65,
    vitD: 0,
    vitB12: 0,
    folate: 108,
    vitA: 77,
  },
  tomato: {
    n: 'Tomato (raw)',
    cat: 'Vegetables',
    ico: '🍅',
    w: 120,
    u: 'piece',
    cal: 22,
    pro: 1.1,
    carb: 4.7,
    fat: 0.2,
    fib: 1.4,
    sug: 3.2,
    sod: 6,
    pot: 285,
    cal_m: 12,
    iron: 0.3,
    mag: 13,
    vitC: 16,
    vitD: 0,
    vitB12: 0,
    folate: 18,
    vitA: 50,
  },

  /* ── Fruits (3) ────────────────────────────────────────────── */
  banana: {
    n: 'Banana',
    cat: 'Fruits',
    ico: '🍌',
    w: 120,
    u: 'piece',
    cal: 105,
    pro: 1.3,
    carb: 27.0,
    fat: 0.4,
    fib: 3.1,
    sug: 14.4,
    sod: 1,
    pot: 422,
    cal_m: 6,
    iron: 0.3,
    mag: 32,
    vitC: 10,
    vitD: 0,
    vitB12: 0,
    folate: 24,
    vitA: 4,
  },
  papaya: {
    n: 'Papaya',
    cat: 'Fruits',
    ico: '🥭',
    w: 150,
    u: 'katori',
    cal: 60,
    pro: 0.7,
    carb: 15.0,
    fat: 0.2,
    fib: 2.5,
    sug: 11.0,
    sod: 4,
    pot: 264,
    cal_m: 30,
    iron: 0.4,
    mag: 15,
    vitC: 88,
    vitD: 0,
    vitB12: 0,
    folate: 56,
    vitA: 68,
  },
  guava: {
    n: 'Guava',
    cat: 'Fruits',
    ico: '🍐',
    w: 100,
    u: 'piece',
    cal: 68,
    pro: 2.6,
    carb: 14.3,
    fat: 1.0,
    fib: 5.4,
    sug: 8.9,
    sod: 2,
    pot: 417,
    cal_m: 18,
    iron: 0.3,
    mag: 22,
    vitC: 228,
    vitD: 0,
    vitB12: 0,
    folate: 49,
    vitA: 31,
  },

  /* ── Dairy (3) ─────────────────────────────────────────────── */
  milk_fullcream: {
    n: 'Full Cream Milk',
    cat: 'Dairy',
    ico: '🥛',
    w: 200,
    u: 'glass',
    cal: 130,
    pro: 6.6,
    carb: 9.4,
    fat: 7.4,
    fib: 0,
    sug: 9.4,
    sod: 98,
    pot: 264,
    cal_m: 234,
    iron: 0.1,
    mag: 22,
    vitC: 0,
    vitD: 100,
    vitB12: 0.9,
    folate: 10,
    vitA: 68,
  },
  curd: {
    n: 'Curd (plain)',
    cat: 'Dairy',
    ico: '🍶',
    w: 100,
    u: 'katori',
    cal: 60,
    pro: 3.5,
    carb: 4.7,
    fat: 3.3,
    fib: 0,
    sug: 4.7,
    sod: 46,
    pot: 155,
    cal_m: 121,
    iron: 0.1,
    mag: 12,
    vitC: 1,
    vitD: 2,
    vitB12: 0.4,
    folate: 7,
    vitA: 27,
  },
  paneer: {
    n: 'Paneer (fresh)',
    cat: 'Dairy',
    ico: '🧀',
    w: 50,
    u: 'piece',
    cal: 132,
    pro: 9.0,
    carb: 1.2,
    fat: 10.5,
    fib: 0,
    sug: 0.5,
    sod: 18,
    pot: 50,
    cal_m: 208,
    iron: 0.2,
    mag: 8,
    vitC: 0,
    vitD: 8,
    vitB12: 0.5,
    folate: 12,
    vitA: 82,
  },

  /* ── Grains (3) ────────────────────────────────────────────── */
  rice_white: {
    n: 'White Rice (cooked)',
    cat: 'Grains',
    ico: '🍚',
    w: 150,
    u: 'katori',
    cal: 195,
    pro: 4.0,
    carb: 43.0,
    fat: 0.4,
    fib: 0.6,
    sug: 0.1,
    sod: 2,
    pot: 55,
    cal_m: 10,
    iron: 1.5,
    mag: 12,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 58,
    vitA: 0,
  },
  rice_brown: {
    n: 'Brown Rice (cooked)',
    cat: 'Grains',
    ico: '🍘',
    w: 150,
    u: 'katori',
    cal: 170,
    pro: 4.5,
    carb: 36.0,
    fat: 1.5,
    fib: 2.5,
    sug: 0.4,
    sod: 5,
    pot: 120,
    cal_m: 12,
    iron: 0.8,
    mag: 44,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 10,
    vitA: 0,
  },
  oats_cooked: {
    n: 'Oats (cooked)',
    cat: 'Grains',
    ico: '🥣',
    w: 175,
    u: 'katori',
    cal: 155,
    pro: 5.5,
    carb: 27.0,
    fat: 2.8,
    fib: 4.0,
    sug: 1.1,
    sod: 4,
    pot: 143,
    cal_m: 18,
    iron: 1.7,
    mag: 40,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 14,
    vitA: 0,
  },

  /* ── Legumes (3) ───────────────────────────────────────────── */
  rajma: {
    n: 'Rajma (cooked)',
    cat: 'Legumes',
    ico: '🫘',
    w: 150,
    u: 'katori',
    cal: 160,
    pro: 9.0,
    carb: 24.0,
    fat: 2.5,
    fib: 6.5,
    sug: 1.5,
    sod: 380,
    pot: 405,
    cal_m: 40,
    iron: 2.8,
    mag: 42,
    vitC: 2,
    vitD: 0,
    vitB12: 0,
    folate: 95,
    vitA: 5,
  },
  chickpeas: {
    n: 'Chickpeas (cooked)',
    cat: 'Legumes',
    ico: '🫘',
    w: 150,
    u: 'katori',
    cal: 180,
    pro: 10.0,
    carb: 27.0,
    fat: 3.5,
    fib: 7.0,
    sug: 3.2,
    sod: 310,
    pot: 360,
    cal_m: 48,
    iron: 3.0,
    mag: 48,
    vitC: 1,
    vitD: 0,
    vitB12: 0,
    folate: 110,
    vitA: 3,
  },
  masoor_dal: {
    n: 'Masoor Dal (cooked)',
    cat: 'Legumes',
    ico: '🍲',
    w: 150,
    u: 'katori',
    cal: 145,
    pro: 9.5,
    carb: 22.0,
    fat: 1.8,
    fib: 5.5,
    sug: 1.2,
    sod: 340,
    pot: 370,
    cal_m: 25,
    iron: 3.3,
    mag: 36,
    vitC: 2,
    vitD: 0,
    vitB12: 0,
    folate: 120,
    vitA: 4,
  },

  /* ── Snacks / Nuts (2) ─────────────────────────────────────── */
  biscuit: {
    n: 'Digestive Biscuit',
    cat: 'Snacks',
    ico: '🍪',
    w: 15,
    u: 'piece',
    cal: 68,
    pro: 1.0,
    carb: 10.0,
    fat: 2.8,
    fib: 0.5,
    sug: 3.0,
    sod: 85,
    pot: 22,
    cal_m: 8,
    iron: 0.4,
    mag: 5,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 4,
    vitA: 0,
  },
  almonds: {
    n: 'Almonds',
    cat: 'Nuts & Seeds',
    ico: '🌰',
    w: 28,
    u: 'serving',
    cal: 164,
    pro: 6.0,
    carb: 6.0,
    fat: 14.0,
    fib: 3.5,
    sug: 1.2,
    sod: 1,
    pot: 208,
    cal_m: 76,
    iron: 1.0,
    mag: 77,
    vitC: 0,
    vitD: 0,
    vitB12: 0,
    folate: 12,
    vitA: 0,
  },

  /* ── Beverages (2) ─────────────────────────────────────────── */
  chai_milk: {
    n: 'Chai (milk tea)',
    cat: 'Beverages',
    ico: '☕',
    w: 150,
    u: 'cup',
    cal: 72,
    pro: 2.5,
    carb: 9.5,
    fat: 2.8,
    fib: 0,
    sug: 7.0,
    sod: 48,
    pot: 85,
    cal_m: 78,
    iron: 0.2,
    mag: 8,
    vitC: 0,
    vitD: 5,
    vitB12: 0.2,
    folate: 4,
    vitA: 22,
  },
  coconut_water: {
    n: 'Coconut Water',
    cat: 'Beverages',
    ico: '🥥',
    w: 240,
    u: 'glass',
    cal: 46,
    pro: 1.7,
    carb: 9.0,
    fat: 0.5,
    fib: 2.6,
    sug: 6.3,
    sod: 252,
    pot: 600,
    cal_m: 58,
    iron: 0.7,
    mag: 60,
    vitC: 6,
    vitD: 0,
    vitB12: 0,
    folate: 7,
    vitA: 0,
  },
};

/* ───────────────────────────────────────────────────────────────
   4. DEFAULT_MEALS — 5 meal slots with preset entries
   ─────────────────────────────────────────────────────────────── */
const DEFAULT_MEALS = [
  {
    id: 'breakfast',
    name: 'Breakfast',
    ico: '🌅',
    entries: [
      { fid: 'idli', qty: 3, note: 'With sambar' },
      { fid: 'sambar', qty: 1, note: '' },
      { fid: 'coconut_chutney', qty: 2, note: '' },
      { fid: 'chai_milk', qty: 1, note: '1 tsp sugar' },
    ],
  },
  {
    id: 'midmorning',
    name: 'Mid Morning',
    ico: '🤗',
    entries: [],
  },
  {
    id: 'lunch',
    name: 'Lunch',
    ico: '☀️',
    entries: [
      { fid: 'rice_brown', qty: 1, note: '' },
      { fid: 'dal_tadka', qty: 1, note: '' },
      { fid: 'spinach', qty: 1, note: 'Palak sabzi' },
      { fid: 'curd', qty: 1, note: '' },
    ],
  },
  {
    id: 'snack',
    name: 'Afternoon Snack',
    ico: '🍵',
    entries: [
      { fid: 'almonds', qty: 1, note: '' },
      { fid: 'guava', qty: 1, note: '' },
    ],
  },
  {
    id: 'dinner',
    name: 'Dinner',
    ico: '🌙',
    entries: [],
  },
];

/* ───────────────────────────────────────────────────────────────
   5. FOOD_CATEGORIES
   ─────────────────────────────────────────────────────────────── */
const FOOD_CATEGORIES = [
  'All',
  'South Indian',
  'North Indian',
  'Protein',
  'Vegetables',
  'Fruits',
  'Dairy',
  'Grains',
  'Legumes',
  'Snacks',
  'Nuts & Seeds',
  'Beverages',
];

/* ───────────────────────────────────────────────────────────────
   6. WATER_STATE — default hydration tracking
   ─────────────────────────────────────────────────────────────── */
const WATER_STATE = { glasses: 4, goalGlasses: 10, glassML: 250 };

/* ───────────────────────────────────────────────────────────────
   7. TREND_HISTORY — 14 days of simulated nutrition data
   ─────────────────────────────────────────────────────────────── */
const TREND_HISTORY = [
  { date: '2026-03-13', cal: 1580, pro: 58, carb: 180, fat: 50, fib: 24, sod: 1420, mag: 280, vitD: 120 },
  { date: '2026-03-14', cal: 1720, pro: 62, carb: 198, fat: 56, fib: 22, sod: 1680, mag: 260, vitD: 80 },
  { date: '2026-03-15', cal: 1610, pro: 70, carb: 172, fat: 52, fib: 30, sod: 1350, mag: 310, vitD: 160 },
  { date: '2026-03-16', cal: 1490, pro: 55, carb: 168, fat: 48, fib: 26, sod: 1280, mag: 290, vitD: 90 },
  { date: '2026-03-17', cal: 1750, pro: 68, carb: 200, fat: 58, fib: 20, sod: 1800, mag: 245, vitD: 110 },
  { date: '2026-03-18', cal: 1640, pro: 64, carb: 185, fat: 54, fib: 28, sod: 1500, mag: 320, vitD: 140 },
  { date: '2026-03-19', cal: 1550, pro: 60, carb: 175, fat: 51, fib: 25, sod: 1380, mag: 305, vitD: 100 },
  { date: '2026-03-20', cal: 1690, pro: 66, carb: 190, fat: 55, fib: 27, sod: 1560, mag: 295, vitD: 130 },
  { date: '2026-03-21', cal: 1800, pro: 72, carb: 210, fat: 60, fib: 19, sod: 1900, mag: 240, vitD: 70 },
  { date: '2026-03-22', cal: 1620, pro: 63, carb: 182, fat: 53, fib: 29, sod: 1440, mag: 315, vitD: 150 },
  { date: '2026-03-23', cal: 1570, pro: 59, carb: 178, fat: 50, fib: 26, sod: 1360, mag: 300, vitD: 105 },
  { date: '2026-03-24', cal: 1680, pro: 67, carb: 192, fat: 56, fib: 23, sod: 1620, mag: 270, vitD: 85 },
  { date: '2026-03-25', cal: 1530, pro: 61, carb: 170, fat: 49, fib: 31, sod: 1300, mag: 330, vitD: 170 },
  { date: '2026-03-26', cal: 1650, pro: 65, carb: 185, fat: 55, fib: 28, sod: 1500, mag: 320, vitD: 140 },
];

/* ───────────────────────────────────────────────────────────────
   8. HELPER FUNCTIONS
   ─────────────────────────────────────────────────────────────── */

/** Nutrient keys to aggregate */
const _NUTRIENT_KEYS = [
  'cal', 'pro', 'carb', 'fat', 'fib', 'sug',
  'sod', 'pot', 'cal_m', 'iron', 'mag',
  'vitC', 'vitD', 'vitB12', 'folate', 'vitA',
];

/**
 * Calculate nutrition for `qty` servings of the food with id `fid`.
 * Returns an object with every nutrient value multiplied by qty,
 * plus `n` (name) and `fid` for convenience.
 */
function calcEntry(fid, qty) {
  const food = FOOD_DB[fid];
  if (!food) return null;
  const result = { fid, n: food.n };
  _NUTRIENT_KEYS.forEach(k => {
    result[k] = Math.round(((food[k] || 0) * qty) * 10) / 10;
  });
  return result;
}

/**
 * Sum nutrition across an array of meal entries
 * Each entry: { fid, qty, note? }
 */
function calcMeal(entries) {
  const totals = {};
  _NUTRIENT_KEYS.forEach(k => { totals[k] = 0; });
  if (!entries || !entries.length) return totals;
  entries.forEach(e => {
    const vals = calcEntry(e.fid, e.qty);
    if (!vals) return;
    _NUTRIENT_KEYS.forEach(k => {
      totals[k] += vals[k] || 0;
    });
  });
  // round to 1 decimal
  _NUTRIENT_KEYS.forEach(k => {
    totals[k] = Math.round(totals[k] * 10) / 10;
  });
  return totals;
}

/**
 * Sum nutrition across all meals (array of meal objects).
 * Each meal: { id, name, ico, entries: [...] }
 */
function calcTotal(meals) {
  const totals = {};
  _NUTRIENT_KEYS.forEach(k => { totals[k] = 0; });
  if (!meals || !meals.length) return totals;
  meals.forEach(meal => {
    const mealTotals = calcMeal(meal.entries);
    _NUTRIENT_KEYS.forEach(k => {
      totals[k] += mealTotals[k] || 0;
    });
  });
  _NUTRIENT_KEYS.forEach(k => {
    totals[k] = Math.round(totals[k] * 10) / 10;
  });
  return totals;
}

/* ───────────────────────────────────────────────────────────────
   EXPORTS
   ─────────────────────────────────────────────────────────────── */
module.exports = {
  FOOD_USER,
  NUTRITION_GOALS,
  FOOD_DB,
  DEFAULT_MEALS,
  FOOD_CATEGORIES,
  WATER_STATE,
  TREND_HISTORY,
  calcEntry,
  calcMeal,
  calcTotal,
};
