const MEDICATIONS = [
  {
    id: 'metformin',
    name: 'Metformin',
    brand: 'Glucophage / Glycomet',
    dose: '500mg',
    form: 'tablet',
    ico: '🔵',
    col: '#3b82f6',
    category: 'Antidiabetic',
    type: 'prescription',
    times: [
      { t: '08:00', label: 'With breakfast', taken: true },
      { t: '20:00', label: 'With dinner', taken: false },
    ],
    frequency: 'Twice daily (BD)',
    withFood: true,
    prescribedBy: 'Dr. Meera Mehta',
    prescribedDate: 'Jan 2025',
    refillDays: 5,
    totalStock: 60,
    usedStock: 55,
    notes: 'Take with first bite of food. Do not crush or chew.',
    purpose:
      'Controls blood sugar by reducing liver glucose production and improving insulin sensitivity.',
    sideEffects:
      'Nausea, diarrhoea (usually settles), metallic taste, B12 depletion (long-term)',
    streak: 22,
    adherence: 94,
    history: Array.from({ length: 30 }, (_, i) =>
      i < 3 ? 'missed' : i === 7 ? 'missed' : 'taken',
    ),
    interactions: ['alcohol', 'contrast-dye', 'ibuprofen'],
    prescriptionDays: 365,
    prescriptionStartDate: '15 Jan 2025',
    prescriptionEndDate: '14 Jan 2026',
    rxNumber: 'RX-2025-0011',
    hospital: 'Yashoda Hospitals, Hyderabad',
    refillHistory: [
      {date: '15 Jan 2025', qty: 60, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 168, invoice: 'INV-001'},
      {date: '14 Feb 2025', qty: 60, store: 'MedPlus, Hitech City', method: 'Delivery', cost: 156, invoice: 'INV-018'},
      {date: '16 Mar 2025', qty: 60, store: 'PharmEasy (online)', method: 'Delivery', cost: 148, invoice: 'INV-037'},
      {date: '12 Apr 2025', qty: 60, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 168, invoice: 'INV-055'},
      {date: '10 May 2025', qty: 60, store: '1mg (online)', method: 'Delivery', cost: 140, invoice: 'INV-073'},
      {date: '08 Jun 2025', qty: 60, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 168, invoice: 'INV-090'},
      {date: '04 Jul 2025', qty: 60, store: 'PharmEasy (online)', method: 'Delivery', cost: 135, invoice: 'INV-108'},
      {date: '31 Jul 2025', qty: 60, store: 'MedPlus, Hitech City', method: 'Delivery', cost: 156, invoice: 'INV-124'},
      {date: '28 Aug 2025', qty: 60, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 168, invoice: 'INV-141'},
      {date: '22 Sep 2025', qty: 60, store: '1mg (online)', method: 'Delivery', cost: 138, invoice: 'INV-159'},
      {date: '17 Oct 2025', qty: 60, store: 'PharmEasy (online)', method: 'Delivery', cost: 132, invoice: 'INV-178'},
      {date: '13 Nov 2025', qty: 60, store: 'Sasta Sundar Dawai', method: 'In-store', cost: 96, invoice: 'INV-196', generic: true},
      {date: '10 Dec 2025', qty: 60, store: 'Sasta Sundar Dawai', method: 'In-store', cost: 96, invoice: 'INV-215', generic: true},
      {date: '06 Jan 2026', qty: 60, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 168, invoice: 'INV-233'},
      {date: '01 Feb 2026', qty: 60, store: 'PharmEasy (online)', method: 'Delivery', cost: 130, invoice: 'INV-250'},
      {date: '26 Feb 2026', qty: 60, store: 'Apollo Pharmacy, Secunderabad', method: 'Pickup', cost: 168, invoice: 'INV-268'},
    ],
  },
  {
    id: 'amlodipine',
    name: 'Amlodipine',
    brand: 'Norvasc / Amlovas',
    dose: '5mg',
    form: 'tablet',
    ico: '🟠',
    col: '#f97316',
    category: 'Antihypertensive',
    type: 'prescription',
    times: [{ t: '08:00', label: 'Any time — morning preferred', taken: true }],
    frequency: 'Once daily (OD)',
    withFood: false,
    prescribedBy: 'Dr. Meera Mehta',
    prescribedDate: 'Jan 2025',
    refillDays: 5,
    totalStock: 30,
    usedStock: 28,
    notes:
      'Can be taken with or without food. Take at same time every day. Do not stop suddenly.',
    purpose:
      'Calcium channel blocker — relaxes blood vessel walls to lower blood pressure.',
    sideEffects:
      'Ankle swelling (20% of patients), facial flushing, headache, dizziness',
    streak: 30,
    adherence: 98,
    history: Array.from({ length: 30 }, () => 'taken'),
    interactions: ['grapefruit', 'simvastatin-high-dose', 'beta-blockers'],
    prescriptionDays: 365,
    prescriptionStartDate: '15 Jan 2025',
    prescriptionEndDate: '14 Jan 2026',
    rxNumber: 'RX-2025-0012',
    hospital: 'Yashoda Hospitals, Hyderabad',
    refillHistory: [
      {date: '15 Jan 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-002'},
      {date: '14 Feb 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-019'},
      {date: '16 Mar 2025', qty: 30, store: 'MedPlus, Hitech City', method: 'Delivery', cost: 148, invoice: 'INV-038'},
      {date: '12 Apr 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-056'},
      {date: '10 May 2025', qty: 30, store: '1mg (online)', method: 'Delivery', cost: 140, invoice: 'INV-074'},
      {date: '08 Jun 2025', qty: 30, store: 'PharmEasy (online)', method: 'Delivery', cost: 136, invoice: 'INV-091'},
      {date: '04 Jul 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-109'},
      {date: '31 Jul 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-125'},
      {date: '28 Aug 2025', qty: 30, store: 'MedPlus, Hitech City', method: 'Delivery', cost: 148, invoice: 'INV-142'},
      {date: '22 Sep 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-160'},
      {date: '17 Oct 2025', qty: 30, store: '1mg (online)', method: 'Delivery', cost: 138, invoice: 'INV-179'},
      {date: '13 Nov 2025', qty: 30, store: 'PharmEasy (online)', method: 'Delivery', cost: 134, invoice: 'INV-197'},
      {date: '10 Dec 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-216'},
      {date: '06 Jan 2026', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 156, invoice: 'INV-234'},
      {date: '01 Feb 2026', qty: 30, store: 'MedPlus, Hitech City', method: 'Delivery', cost: 148, invoice: 'INV-251'},
      {date: '26 Feb 2026', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'Pickup', cost: 156, invoice: 'INV-269'},
    ],
  },
  {
    id: 'atorvastatin',
    name: 'Atorvastatin',
    brand: 'Lipitor / Storvas',
    dose: '10mg',
    form: 'tablet',
    ico: '🟡',
    col: '#f59e0b',
    category: 'Statin / Lipid-lowering',
    type: 'prescription',
    times: [{ t: '21:00', label: 'At night — best absorbed', taken: false }],
    frequency: 'Once daily (OD) — evening',
    withFood: false,
    prescribedBy: 'Dr. Meera Mehta',
    prescribedDate: 'Jan 2025',
    refillDays: 5,
    totalStock: 30,
    usedStock: 27,
    notes:
      'Best taken at night when liver produces most cholesterol. Avoid grapefruit juice.',
    purpose:
      'Reduces LDL cholesterol and triglycerides; reduces cardiovascular event risk.',
    sideEffects:
      'Muscle aches (rare at 10mg), liver enzyme changes (monitor 6-monthly)',
    streak: 28,
    adherence: 95,
    history: Array.from({ length: 30 }, (_, i) =>
      i === 4 || i === 18 ? 'missed' : 'taken',
    ),
    interactions: ['grapefruit', 'gemfibrozil', 'antifungals', 'clarithromycin'],
    prescriptionDays: 365,
    prescriptionStartDate: '15 Jan 2025',
    prescriptionEndDate: '14 Jan 2026',
    rxNumber: 'RX-2025-0013',
    hospital: 'Yashoda Hospitals, Hyderabad',
    refillHistory: [
      {date: '15 Jan 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 285, invoice: 'INV-003'},
      {date: '14 Feb 2025', qty: 30, store: '1mg (online)', method: 'Delivery', cost: 262, invoice: 'INV-020'},
      {date: '16 Mar 2025', qty: 30, store: 'PharmEasy (online)', method: 'Delivery', cost: 255, invoice: 'INV-039'},
      {date: '12 Apr 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 285, invoice: 'INV-057'},
      {date: '10 May 2025', qty: 30, store: 'Sasta Sundar Dawai', method: 'In-store', cost: 66, invoice: 'INV-075', generic: true},
      {date: '08 Jun 2025', qty: 30, store: 'Sasta Sundar Dawai', method: 'In-store', cost: 66, invoice: 'INV-092', generic: true},
      {date: '04 Jul 2025', qty: 30, store: '1mg (online)', method: 'Delivery', cost: 258, invoice: 'INV-110'},
      {date: '31 Jul 2025', qty: 30, store: 'PharmEasy (online)', method: 'Delivery', cost: 250, invoice: 'INV-126'},
      {date: '28 Aug 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 285, invoice: 'INV-143'},
      {date: '01 Feb 2026', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 285, invoice: 'INV-252'},
      {date: '26 Feb 2026', qty: 30, store: '1mg (online)', method: 'Delivery', cost: 255, invoice: 'INV-270'},
    ],
  },
  {
    id: 'methylcobalamin',
    name: 'Methylcobalamin',
    brand: 'Mecobalamin / Methycobal',
    dose: '500mcg',
    form: 'tablet',
    ico: '🟣',
    col: '#a855f7',
    category: 'Vitamin B12 supplement',
    type: 'prescription',
    times: [{ t: '08:00', label: 'With breakfast', taken: true }],
    frequency: 'Once daily (OD)',
    withFood: true,
    prescribedBy: 'Dr. Meera Mehta',
    prescribedDate: 'Jan 2025',
    refillDays: 12,
    totalStock: 30,
    usedStock: 18,
    notes:
      'Active form of B12. Prescribed to counteract Metformin-induced B12 depletion.',
    purpose:
      'Prevents peripheral neuropathy and neurological damage caused by Metformin-depleted B12.',
    sideEffects: 'Generally very well tolerated. Rare: mild nausea.',
    streak: 18,
    adherence: 88,
    history: Array.from({ length: 30 }, (_, i) =>
      i === 2 || i === 11 || i === 22 ? 'missed' : 'taken',
    ),
    interactions: [],
    prescriptionDays: 365,
    prescriptionStartDate: '15 Jan 2025',
    prescriptionEndDate: '14 Jan 2026',
    rxNumber: 'RX-2025-0014',
    hospital: 'Yashoda Hospitals, Hyderabad',
    refillHistory: [
      {date: '15 Jan 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 444, invoice: 'INV-004'},
      {date: '16 Mar 2025', qty: 30, store: 'MedPlus, Hitech City', method: 'Delivery', cost: 420, invoice: 'INV-040'},
      {date: '12 May 2025', qty: 30, store: 'PharmEasy (online)', method: 'Delivery', cost: 405, invoice: 'INV-076'},
      {date: '10 Jul 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 444, invoice: 'INV-111'},
      {date: '08 Sep 2025', qty: 30, store: '1mg (online)', method: 'Delivery', cost: 415, invoice: 'INV-161'},
      {date: '06 Nov 2025', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 444, invoice: 'INV-199'},
      {date: '04 Jan 2026', qty: 30, store: 'MedPlus, Hitech City', method: 'Delivery', cost: 420, invoice: 'INV-235'},
      {date: '01 Mar 2026', qty: 30, store: 'Apollo Pharmacy, Secunderabad', method: 'In-store', cost: 444, invoice: 'INV-271'},
    ],
  },
  {
    id: 'vitD3',
    name: 'Vitamin D3',
    brand: 'Calcirol / Cholecalciferol',
    dose: '1000 IU',
    form: 'softgel',
    ico: '☀️',
    col: '#eab308',
    category: 'Supplement',
    type: 'supplement',
    times: [{ t: '08:00', label: 'With fatty meal', taken: true }],
    frequency: 'Once daily',
    withFood: true,
    prescribedBy: 'Self / Ayu recommendation',
    prescribedDate: 'Mar 2026',
    refillDays: 20,
    totalStock: 60,
    usedStock: 6,
    notes:
      'Take with a meal containing fat for best absorption. Critical for insulin sensitivity.',
    purpose:
      'Corrects Vitamin D deficiency — improves insulin sensitivity, immune function.',
    sideEffects:
      'Safe at 1000 IU. Toxicity only with very high doses (>10,000 IU/day).',
    streak: 6,
    adherence: 100,
    history: Array.from({ length: 30 }, (_, i) =>
      i < 24 ? 'na' : i === 27 ? 'missed' : 'taken',
    ),
    interactions: ['thiazide-diuretics'],
    prescriptionDays: 90,
    prescriptionStartDate: '01 Mar 2026',
    prescriptionEndDate: '29 May 2026',
    rxNumber: 'AYU-2026-001',
    hospital: 'Ayu recommendation (self-purchased)',
    refillHistory: [
      {date: '01 Mar 2026', qty: 60, store: '1mg (online)', method: 'Delivery', cost: 360, invoice: 'INV-272'},
    ],
  },
];

const DRUG_INTERACTIONS = [
  {
    sev: 'moderate',
    col: '#f97316',
    title: 'Metformin + Alcohol',
    body: 'Alcohol increases the risk of lactic acidosis with Metformin. Limit intake to occasional small amounts with food. Avoid binge drinking entirely.',
  },
  {
    sev: 'moderate',
    col: '#f97316',
    title: 'Atorvastatin + Grapefruit',
    body: 'Grapefruit juice inhibits CYP3A4, increasing Atorvastatin blood levels and risk of muscle damage (rhabdomyolysis). Avoid grapefruit entirely.',
  },
  {
    sev: 'monitor',
    col: '#3b82f6',
    title: 'Amlodipine + Atorvastatin (high dose)',
    body: 'Both metabolised by CYP3A4. At high statin doses (>20mg), Amlodipine can raise statin levels. Current 10mg dose is safe — no action needed.',
  },
  {
    sev: 'low',
    col: '#22c55e',
    title: 'Vitamin D3 + Atorvastatin (beneficial)',
    body: 'Vitamin D may reduce statin-related muscle pain. Correcting D deficiency supports better statin tolerability. Beneficial combination.',
  },
  {
    sev: 'moderate',
    col: '#f97316',
    title: 'Metformin + NSAIDs (e.g. Ibuprofen)',
    body: 'NSAIDs can impair kidney function, reducing Metformin clearance and increasing lactic acidosis risk. Use Paracetamol instead when possible.',
  },
];

const TIMING_TIPS = [
  {
    ico: '🍳',
    title: 'Morning cluster — take with breakfast',
    status: 'good',
    body: 'Metformin, Methylcobalamin, and Vitamin D3 all benefit from food. Taking together at 8 AM with a fatty breakfast maximises absorption.',
  },
  {
    ico: '🌙',
    title: 'Atorvastatin at night',
    status: 'good',
    body: 'Cholesterol synthesis peaks overnight. Taking your statin at 9 PM aligns with your body\'s natural rhythm for best LDL reduction.',
  },
  {
    ico: '⏰',
    title: 'Amlodipine — consistent timing matters',
    status: 'warning',
    body: 'Blood pressure control depends on steady drug levels. Taking Amlodipine at varying times reduces 24-hour coverage. Stick to 8 AM daily.',
  },
  {
    ico: '🥛',
    title: 'Vitamin D3 needs fat to absorb',
    status: 'info',
    body: 'Vitamin D is fat-soluble. Taking with a dry roti or plain tea reduces absorption by up to 50%. Pair with ghee, nuts, or egg.',
  },
  {
    ico: '🍽️',
    title: 'Metformin — first bite rule',
    status: 'warning',
    body: 'Taking Metformin on an empty stomach increases GI side effects. Always take with the first bite of your meal to reduce nausea and diarrhoea.',
  },
];

const SIDE_EFFECTS_WATCH = [
  {
    ico: '🦶',
    sev: 'monitor',
    title: 'Tingling / numbness in feet',
    body: 'Could indicate B12 deficiency from long-term Metformin. Methylcobalamin prescribed to prevent this. Report if symptoms appear.',
    col: '#a855f7',
  },
  {
    ico: '🦵',
    sev: 'watch',
    title: 'Muscle aches or weakness',
    body: 'Rare with Atorvastatin 10mg but important to monitor. Report unexplained muscle pain — CK levels may need checking.',
    col: '#f59e0b',
  },
  {
    ico: '🦶',
    sev: 'common',
    title: 'Ankle swelling',
    body: 'Affects ~20% of Amlodipine users. Mild swelling is expected. Elevate legs when resting. Report if severe or painful.',
    col: '#f97316',
  },
  {
    ico: '🤢',
    sev: 'settling',
    title: 'GI discomfort (Metformin)',
    body: 'Nausea, bloating, and loose stools are common initially but usually settle within 2–4 weeks. Take with food to minimise.',
    col: '#3b82f6',
  },
];

const BIOMARKER_IMPACT = [
  {medId: 'metformin', med: 'Metformin', adh: 94, bio: 'HbA1c', current: '7.8%', projected: '7.2%', col: '#3b82f6'},
  {medId: 'amlodipine', med: 'Amlodipine', adh: 98, bio: 'Systolic BP', current: '140 mmHg', projected: '126 mmHg', col: '#f97316'},
  {medId: 'atorvastatin', med: 'Atorvastatin', adh: 95, bio: 'LDL', current: '112 mg/dL', projected: '72 mg/dL', col: '#f59e0b'},
  {medId: 'methylcobalamin', med: 'Methylcobalamin', adh: 88, bio: 'B12 level', current: 'Borderline', projected: 'Adequate', col: '#a855f7'},
];

const IMPORT_OPTIONS = [
  {
    ico: '📷',
    col: '#3b82f6',
    title: 'Scan Rx',
    sub: 'Photograph prescription',
  },
  {
    ico: '🏥',
    col: '#1D9E75',
    title: 'Pharmacy',
    sub: 'Scan receipt / barcode',
  },
  {
    ico: '📋',
    col: '#a855f7',
    title: 'e-Prescription',
    sub: 'Import from hospital',
  },
];

const AYU_MED_INSIGHTS = {
  metformin: 'Priya, Metformin adherence at 94% means approximately 2 missed doses per month. Each missed dose raises next-day fasting glucose by 15-25 mg/dL. With your current streak of 22 days, you\'re building strong habit momentum. Your next refill is due in ~5 days.',
  amlodipine: 'Priya, Amlodipine at 98% adherence is excellent. As a calcium channel blocker, missing even 1-2 doses can cause a hypertensive rebound. Your 30-day unbroken streak is protecting your cardiovascular health every day. Do not stop this medication without Dr. Mehta\'s guidance.',
  atorvastatin: 'Priya, Atorvastatin is most effective taken at 9 PM when your liver is most active in cholesterol synthesis. Your adherence of 95% is very good. Avoid grapefruit entirely - it raises Atorvastatin blood levels by up to 83%, increasing side effect risk.',
  methylcobalamin: 'Priya, Methylcobalamin is prescribed specifically to counteract Metformin-induced B12 depletion. At 88% adherence, some B12 depletion risk remains. Even 3 missed doses a month compounds over time. Consider combining it with your 8 AM Metformin dose to build a consistent routine.',
  vitD3: 'Priya, Vitamin D3 was added based on Ayu\'s analysis of your nutritional profile. As a fat-soluble vitamin, consistent daily intake with a fatty meal (like your breakfast) maximises absorption. Your 6-day streak since starting is a great beginning.',
};

module.exports = {
  MEDICATIONS,
  DRUG_INTERACTIONS,
  TIMING_TIPS,
  SIDE_EFFECTS_WATCH,
  BIOMARKER_IMPACT,
  IMPORT_OPTIONS,
  AYU_MED_INSIGHTS,
};
