/* ================================================================
   recordsFinalData.js
   Comprehensive data for the Records screen
   – 5 main tabs, ribbon filters, stats, and record entries
   ================================================================ */

// ─── 1. MAIN TABS ──────────────────────────────────────────────
const MAIN_TABS = [
  { key: 'medical',   label: 'Medical',       ico: 'medical-outline' },
  { key: 'logs',      label: 'Health logs',   ico: 'pulse-outline' },
  { key: 'bills',     label: 'Service bills', ico: 'receipt-outline' },
  { key: 'gadgets',   label: 'Gadgets',       ico: 'phone-portrait-outline' },
  { key: 'insurance', label: 'Insurance',     ico: 'shield-checkmark-outline' },
];

// ─── 2. RIBBON FILTERS ─────────────────────────────────────────
const RIBBON_FILTERS = {
  medical: [
    { key: 'all',    ico: 'grid-outline',             label: 'All',            count: 38, bg: '#E1F5EE' },
    { key: 'notes',  ico: 'medical-outline',           label: 'Doctor',         count: 9,  bg: '#E1F5EE' },
    { key: 'labs',   ico: 'flask-outline',             label: 'Lab reports',    count: 14, bg: '#FAEEDA' },
    { key: 'imaging',ico: 'scan-outline',              label: 'Imaging',        count: 4,  bg: '#E6F1FB' },
    { key: 'rx',     ico: 'document-text-outline',     label: 'Prescriptions',  count: 8,  bg: '#EEEDFE' },
    { key: 'vax',    ico: 'shield-checkmark-outline',  label: 'Vaccination',    count: 5,  bg: '#E1F5EE' },
    { key: 'tele',   ico: 'videocam-outline',          label: 'Telemedicine',   count: 3,  bg: '#E6F1FB' },
    { key: 'couns',  ico: 'chatbubbles-outline',       label: 'Counselling',    count: 2,  bg: '#EEEDFE' },
    { key: 'physio', ico: 'fitness-outline',           label: 'Physio',         count: 3,  bg: '#E1F5EE' },
    { key: 'nurse',  ico: 'heart-outline',             label: 'Nursing',        count: 2,  bg: '#FBEAF0' },
    { key: 'well',   ico: 'leaf-outline',              label: 'Wellness',       count: 1,  bg: '#E1F5EE' },
  ],
  logs: [
    { key: 'all',      ico: 'grid-outline',       label: 'All',        count: 284, bg: '#E1F5EE' },
    { key: 'glucose',  ico: 'water-outline',       label: 'Glucose',    count: 28,  bg: '#FAEEDA' },
    { key: 'bp',       ico: 'heart-outline',       label: 'BP',         count: 24,  bg: '#FCEBEB' },
    { key: 'meds',     ico: 'medkit-outline',      label: 'Medication', count: 93,  bg: '#EEEDFE' },
    { key: 'sleep',    ico: 'moon-outline',        label: 'Sleep',      count: 28,  bg: '#E6F1FB' },
    { key: 'food',     ico: 'restaurant-outline',  label: 'Food',       count: 71,  bg: '#FAEEDA' },
    { key: 'fitness',  ico: 'barbell-outline',     label: 'Fitness',    count: 18,  bg: '#E1F5EE' },
    { key: 'symptoms', ico: 'bandage-outline',     label: 'Symptoms',   count: 18,  bg: '#FCEBEB' },
    { key: 'mood',     ico: 'happy-outline',       label: 'Mood',       count: 26,  bg: '#EEEDFE' },
    { key: 'weight',   ico: 'scale-outline',       label: 'Weight',     count: 38,  bg: '#E1F5EE' },
  ],
  bills: [
    { key: 'all',  ico: 'grid-outline',      label: 'All bills',  count: 14, bg: '#E1F5EE' },
    { key: 'lab',  ico: 'flask-outline',      label: 'Lab',        count: 2,  bg: '#FAEEDA' },
    { key: 'doc',  ico: 'medical-outline',    label: 'Doctor',     count: 2,  bg: '#E1F5EE' },
    { key: 'med',  ico: 'medkit-outline',     label: 'Medicines',  count: 2,  bg: '#EEEDFE' },
    { key: 'tele', ico: 'videocam-outline',   label: 'Tele',       count: 1,  bg: '#E6F1FB' },
    { key: 'hosp', ico: 'business-outline',   label: 'Hospital',   count: 1,  bg: '#E6F1FB' },
    { key: 'well', ico: 'leaf-outline',       label: 'Wellness',   count: 1,  bg: '#E1F5EE' },
  ],
  gadgets: [
    { key: 'all', ico: 'grid-outline',           label: 'All',        count: 6, bg: '#E6F1FB' },
    { key: 'inv', ico: 'receipt-outline',         label: 'Invoices',   count: 6, bg: '#FAEEDA' },
    { key: 'war', ico: 'shield-outline',          label: 'Warranties', count: 6, bg: '#E1F5EE' },
    { key: 'exp', ico: 'alert-circle-outline',    label: 'Expiring',   count: 3, bg: '#FAEEDA' },
  ],
  insurance: [
    { key: 'all',      ico: 'grid-outline',     label: 'All',      count: 8, bg: '#E1F5EE' },
    { key: 'policies', ico: 'document-outline',  label: 'Policies', count: 1, bg: '#E1F5EE' },
    { key: 'claims',   ico: 'cash-outline',      label: 'Claims',   count: 3, bg: '#FAEEDA' },
    { key: 'premiums', ico: 'card-outline',      label: 'Premiums', count: 1, bg: '#E6F1FB' },
    { key: 'cards',    ico: 'id-card-outline',   label: 'Cards',    count: 1, bg: '#E1F5EE' },
  ],
};

// ─── 3. STATS HEADER ───────────────────────────────────────────
const STATS_HEADER = {
  medical: 38,
  medicalLabel: 'records',
  logs: 284,
  logsLabel: 'tracked',
  bills: 14,
  billsAmount: '\u20B938,470',
  claims: 3,
  claimsAmount: '\u20B912,400',
};

// ─── 4. MEDICAL RECORDS ────────────────────────────────────────
const MEDICAL_RECORDS = [
  // ── March 2026 ──
  {
    id: 'med-001',
    cat: 'physio',
    dateGroup: 'March 2026',
    ico: '\uD83E\uDDBF',
    icoBg: '#E1F5EE',
    title: 'Physiotherapy – Suresh Rao',
    sub: 'Shoulder rehab · 3 sessions completed',
    pillLabel: 'Ongoing',
    pillStyle: 'pg',
    meta: '14 Mar 2026',
    date: '2026-03-14',
    footerTags: [
      { label: 'Rotator cuff', style: 'pg' },
      { label: '3 sessions', style: 'pa' },
    ],
    visitId: 'VIS-PHY-0314',
    linkedCount: 2,
    detailRoute: 'PhysioDetail',
  },
  {
    id: 'med-002',
    cat: 'labs',
    dateGroup: 'March 2026',
    ico: '\uD83E\uDDEA',
    icoBg: '#FAEEDA',
    title: 'Diabetes Panel – Apollo Diagnostics',
    sub: 'HbA1c · FBG · PP glucose · lipid profile',
    pillLabel: 'Abnormal',
    pillStyle: 'pr',
    meta: '12 Mar 2026 · PDF 1.2 MB',
    date: '2026-03-12',
    size: '1.2 MB',
    values: [
      { label: 'HbA1c 7.2%', style: 'pr' },
      { label: 'FBG 128 mg/dL', style: 'pa' },
      { label: 'PP 164 mg/dL', style: 'pr' },
      { label: 'LDL 138 mg/dL', style: 'pa' },
      { label: 'HDL 42 mg/dL', style: 'pa' },
      { label: 'Trigly 178 mg/dL', style: 'pr' },
    ],
    footerTags: [
      { label: 'Diabetes', style: 'pr' },
      { label: 'Lipid', style: 'pa' },
      { label: 'Fasting', style: 'pg' },
    ],
    visitId: 'VIS-LAB-0312',
    linkedCount: 3,
    detailRoute: 'LabReportDetail',
  },
  {
    id: 'med-003',
    cat: 'notes',
    dateGroup: 'March 2026',
    ico: '\uD83E\uDE7A',
    icoBg: '#E1F5EE',
    title: 'Dr. Meera Mehta – Endocrinologist',
    sub: 'Follow-up · diabetes management review',
    pillLabel: 'In-person',
    pillStyle: 'pg',
    meta: '5 Mar 2026 · Yashoda Hospital',
    date: '2026-03-05',
    footerTags: [
      { label: 'Diabetes', style: 'pr' },
      { label: 'Follow-up', style: 'pg' },
      { label: 'Rx updated', style: 'pp' },
    ],
    visitId: 'VIS-DOC-0305',
    linkedCount: 4,
    detailRoute: 'DoctorNoteDetail',
  },
  {
    id: 'med-004',
    cat: 'rx',
    dateGroup: 'March 2026',
    ico: '\uD83D\uDCCB',
    icoBg: '#EEEDFE',
    title: 'Prescription – Dr. Meera Mehta',
    sub: 'Metformin 1000 mg · Glimep 2 mg · Atorva 20 mg',
    pillLabel: 'Active',
    pillStyle: 'pg',
    meta: '5 Mar 2026 · 5 medications',
    date: '2026-03-05',
    footerTags: [
      { label: 'Active', style: 'pg' },
      { label: '5 meds', style: 'pp' },
      { label: '90 days', style: 'pa' },
    ],
    visitId: 'VIS-DOC-0305',
    linkedCount: 2,
    detailRoute: 'PrescriptionDetail',
  },

  // ── February 2026 ──
  {
    id: 'med-005',
    cat: 'well',
    dateGroup: 'February 2026',
    ico: '\uD83C\uDF3F',
    icoBg: '#E1F5EE',
    title: 'Panchakarma – Kairali Ayurveda',
    sub: 'Detox therapy · 3 sessions',
    pillLabel: 'Completed',
    pillStyle: 'pg',
    meta: '20 Feb 2026 · Jubilee Hills',
    date: '2026-02-20',
    footerTags: [
      { label: 'Wellness', style: 'pg' },
      { label: '3 sessions', style: 'pa' },
      { label: 'Ayurveda', style: 'pp' },
    ],
    detailRoute: 'WellnessDetail',
  },

  // ── January 2026 ──
  {
    id: 'med-006',
    cat: 'couns',
    dateGroup: 'January 2026',
    ico: '\uD83E\uDDE0',
    icoBg: '#EEEDFE',
    title: 'Counselling – Nisha Kapoor',
    sub: 'CBT session 4 · stress & sleep management',
    pillLabel: 'Virtual',
    pillStyle: 'pb',
    meta: '22 Jan 2026 · 45 min session',
    date: '2026-01-22',
    footerTags: [
      { label: 'CBT', style: 'pp' },
      { label: 'Stress', style: 'pa' },
      { label: 'Session 4', style: 'pb' },
    ],
    detailRoute: 'CounsellingDetail',
  },
  {
    id: 'med-007',
    cat: 'notes',
    dateGroup: 'January 2026',
    ico: '\uD83E\uDE7A',
    icoBg: '#E1F5EE',
    title: 'Dr. K. Rajan – Cardiologist',
    sub: 'Annual cardiac check-up · ECG normal',
    pillLabel: 'In-person',
    pillStyle: 'pg',
    meta: '17 Jan 2026 · Apollo Hospital',
    date: '2026-01-17',
    footerTags: [
      { label: 'Cardiology', style: 'pb' },
      { label: 'ECG normal', style: 'pg' },
      { label: 'Annual', style: 'pa' },
    ],
    visitId: 'VIS-DOC-0117',
    linkedCount: 3,
    detailRoute: 'DoctorNoteDetail',
  },
  {
    id: 'med-008',
    cat: 'nurse',
    dateGroup: 'January 2026',
    ico: '\uD83C\uDFE5',
    icoBg: '#FBEAF0',
    title: 'Home Nursing – Portea Medical',
    sub: 'Post-op wound dressing · 2 visits',
    pillLabel: 'Completed',
    pillStyle: 'pg',
    meta: '9 Jan 2026 · Home visit',
    date: '2026-01-09',
    footerTags: [
      { label: 'Nursing', style: 'pn' },
      { label: '2 visits', style: 'pa' },
      { label: 'Wound care', style: 'pr' },
    ],
    linkedCount: 2,
    detailRoute: 'NursingDetail',
  },
  {
    id: 'med-009',
    cat: 'labs',
    dateGroup: 'January 2026',
    ico: '\uD83E\uDDEA',
    icoBg: '#FAEEDA',
    title: 'Aarogyam Full Body – Thyrocare',
    sub: '76 tests · CBC, LFT, KFT, thyroid, vitamin panel',
    pillLabel: 'Normal',
    pillStyle: 'pg',
    meta: '8 Jan 2026 · PDF 2.4 MB',
    date: '2026-01-08',
    size: '2.4 MB',
    values: [
      { label: 'TSH 3.1 mIU/L', style: 'pg' },
      { label: 'Vit D 28 ng/mL', style: 'pa' },
      { label: 'B12 312 pg/mL', style: 'pg' },
      { label: 'Creatinine 0.9', style: 'pg' },
      { label: 'Hb 13.8 g/dL', style: 'pg' },
    ],
    footerTags: [
      { label: '76 tests', style: 'pb' },
      { label: 'Annual', style: 'pg' },
      { label: 'Full body', style: 'pa' },
    ],
    visitId: 'VIS-LAB-0108',
    detailRoute: 'LabReportDetail',
  },
  {
    id: 'med-010',
    cat: 'tele',
    dateGroup: 'January 2026',
    ico: '\uD83D\uDCF9',
    icoBg: '#E6F1FB',
    title: 'Dr. Vikram Sinha – Neurologist (Tele)',
    sub: 'Video consult · migraine follow-up',
    pillLabel: 'Teleconsult',
    pillStyle: 'pb',
    meta: '3 Jan 2026 · 20 min call',
    date: '2026-01-03',
    footerTags: [
      { label: 'Neurology', style: 'pb' },
      { label: 'Migraine', style: 'pr' },
      { label: 'Video', style: 'pa' },
    ],
    visitId: 'VIS-TELE-0103',
    linkedCount: 2,
    detailRoute: 'TeleVisitDetail',
  },
  {
    id: 'med-011',
    cat: 'rx',
    dateGroup: 'January 2026',
    ico: '\uD83D\uDCCB',
    icoBg: '#EEEDFE',
    title: 'E-Prescription – Dr. Vikram Sinha',
    sub: 'Sumatriptan 50 mg · Amitriptyline 10 mg',
    pillLabel: 'Active',
    pillStyle: 'pg',
    meta: '3 Jan 2026 · 2 medications',
    date: '2026-01-03',
    footerTags: [
      { label: 'E-Rx', style: 'pb' },
      { label: '2 meds', style: 'pp' },
      { label: '30 days', style: 'pa' },
    ],
    visitId: 'VIS-TELE-0103',
    detailRoute: 'PrescriptionDetail',
  },

  // ── Sep–Dec 2025 ──
  {
    id: 'med-012',
    cat: 'imaging',
    dateGroup: 'Sep-Dec 2025',
    ico: '\uD83D\uDDA5\uFE0F',
    icoBg: '#E6F1FB',
    title: '2D Echocardiogram',
    sub: 'EF 60% · no valvular abnormality · normal LV function',
    pillLabel: 'Normal',
    pillStyle: 'pg',
    meta: '4 Dec 2025 · Apollo Hospital · DICOM',
    date: '2025-12-04',
    size: '18 MB',
    values: [
      { label: 'EF 60%', style: 'pg' },
      { label: 'LV normal', style: 'pg' },
    ],
    footerTags: [
      { label: 'Cardiac', style: 'pb' },
      { label: 'Echo', style: 'pa' },
      { label: 'DICOM', style: 'pm' },
    ],
    visitId: 'VIS-IMG-1204',
    linkedCount: 2,
    detailRoute: 'ImagingDetail',
  },
  {
    id: 'med-013',
    cat: 'imaging',
    dateGroup: 'Sep-Dec 2025',
    ico: '\uD83D\uDDA5\uFE0F',
    icoBg: '#E6F1FB',
    title: 'Chest X-ray (PA view)',
    sub: 'Lungs clear · no cardiomegaly · normal study',
    pillLabel: 'Normal',
    pillStyle: 'pg',
    meta: '4 Dec 2025 · Apollo Hospital · JPEG',
    date: '2025-12-04',
    size: '3.2 MB',
    footerTags: [
      { label: 'Chest', style: 'pb' },
      { label: 'X-ray', style: 'pa' },
      { label: 'Normal', style: 'pg' },
    ],
    visitId: 'VIS-IMG-1204',
    detailRoute: 'ImagingDetail',
  },
  {
    id: 'med-014',
    cat: 'vax',
    dateGroup: 'Sep-Dec 2025',
    ico: '\uD83D\uDC89',
    icoBg: '#E1F5EE',
    title: 'Influenza Vaccine (Quadrivalent)',
    sub: 'Vaxigrip Tetra · Sanofi · Batch VG-2025-IN',
    pillLabel: 'Completed',
    pillStyle: 'pg',
    meta: 'Sep 2025 · Apollo Clinic',
    date: '2025-09-15',
    footerTags: [
      { label: 'Flu', style: 'pb' },
      { label: 'Annual', style: 'pa' },
      { label: 'Sanofi', style: 'pg' },
    ],
    detailRoute: 'VaccinationDetail',
  },
  {
    id: 'med-015',
    cat: 'rx',
    dateGroup: 'Sep-Dec 2025',
    ico: '\uD83D\uDCCB',
    icoBg: '#EEEDFE',
    title: 'Prescription – Dr. Meera Mehta',
    sub: 'Metformin 500 mg · Glimep 1 mg (previous dosage)',
    pillLabel: 'Expired',
    pillStyle: 'pm',
    meta: 'Sep 2025 · replaced by Mar 2026 Rx',
    date: '2025-09-10',
    footerTags: [
      { label: 'Expired', style: 'pm' },
      { label: 'Superseded', style: 'pa' },
    ],
    detailRoute: 'PrescriptionDetail',
  },
  {
    id: 'med-016',
    cat: 'vax',
    dateGroup: 'Sep-Dec 2025',
    ico: '\uD83D\uDC89',
    icoBg: '#E1F5EE',
    title: 'Hepatitis B Vaccine (Dose 3/3)',
    sub: 'Engerix-B · GSK · Batch HB-2022-03',
    pillLabel: 'Completed',
    pillStyle: 'pg',
    meta: 'Mar 2022 · Apollo Clinic',
    date: '2022-03-20',
    footerTags: [
      { label: 'Hep B', style: 'pb' },
      { label: 'Dose 3/3', style: 'pg' },
      { label: 'GSK', style: 'pa' },
    ],
    detailRoute: 'VaccinationDetail',
  },
  {
    id: 'med-017',
    cat: 'vax',
    dateGroup: 'Sep-Dec 2025',
    ico: '\uD83D\uDC89',
    icoBg: '#E1F5EE',
    title: 'COVID-19 Vaccine (Covishield + Booster)',
    sub: 'AstraZeneca · 2 doses + 1 booster · 2021-22',
    pillLabel: 'Completed',
    pillStyle: 'pg',
    meta: '2021-22 · Govt. PHC',
    date: '2022-01-15',
    footerTags: [
      { label: 'COVID-19', style: 'pr' },
      { label: '3 doses', style: 'pg' },
      { label: 'Covishield', style: 'pa' },
    ],
    detailRoute: 'VaccinationDetail',
  },
];

// ─── 5. HEALTH LOGS ────────────────────────────────────────────
const HEALTH_LOGS = [
  {
    id: 'log-001',
    cat: 'lifestyle',
    dateGroup: 'March 2026',
    ico: '\uD83D\uDCCA',
    icoBg: '#E1F5EE',
    title: 'Monthly Lifestyle Snapshot',
    sub: 'Sleep · steps · medication · food tracking',
    pillLabel: 'March 2026',
    pillStyle: 'pg',
    meta: '31 days tracked',
    date: '2026-03-31',
    habitGrid: {
      sleep:      { avg: '6.8h', target: '7.5h', pct: 91, trend: 'up',   color: '#5B8DEF' },
      steps:      { avg: '6,240', target: '8,000', pct: 78, trend: 'down', color: '#34C759' },
      medication: { avg: '94%',  target: '100%', pct: 94, trend: 'up',   color: '#AF52DE' },
      food:       { avg: '71%',  target: '85%',  pct: 84, trend: 'same', color: '#FF9500' },
    },
    footerTags: [
      { label: 'Sleep 6.8h', style: 'pb' },
      { label: 'Steps 6,240', style: 'pg' },
      { label: 'Meds 94%', style: 'pp' },
      { label: 'Food 71%', style: 'pa' },
    ],
    detailRoute: 'LifestyleSnapshotDetail',
  },
  {
    id: 'log-002',
    cat: 'glucose',
    dateGroup: 'March 2026',
    ico: '\uD83E\uDE78',
    icoBg: '#FAEEDA',
    title: 'Blood Glucose Log',
    sub: 'FBG 128 avg · PP 164 avg · TIR 62%',
    pillLabel: 'Above target',
    pillStyle: 'pr',
    meta: '28 readings · March 2026',
    date: '2026-03-31',
    values: [
      { label: 'FBG 128 mg/dL', style: 'pa' },
      { label: 'PP 164 mg/dL', style: 'pr' },
      { label: 'TIR 62%', style: 'pa' },
      { label: '28 readings', style: 'pg' },
    ],
    footerTags: [
      { label: 'Diabetes', style: 'pr' },
      { label: 'Fasting', style: 'pa' },
      { label: 'Post-meal', style: 'pr' },
    ],
    detailRoute: 'GlucoseLogDetail',
  },
  {
    id: 'log-003',
    cat: 'bp',
    dateGroup: 'March 2026',
    ico: '\u2764\uFE0F',
    icoBg: '#FCEBEB',
    title: 'Blood Pressure Log',
    sub: 'Avg 136/86 · peak 148/94 · low 124/78',
    pillLabel: 'Stage 1 HTN',
    pillStyle: 'pa',
    meta: '24 readings · March 2026',
    date: '2026-03-31',
    values: [
      { label: 'Avg 136/86', style: 'pa' },
      { label: 'Peak 148/94', style: 'pr' },
      { label: 'Low 124/78', style: 'pg' },
      { label: 'Pulse 76 bpm', style: 'pg' },
    ],
    footerTags: [
      { label: 'Hypertension', style: 'pr' },
      { label: 'Morning', style: 'pa' },
      { label: 'Evening', style: 'pb' },
    ],
    detailRoute: 'BPLogDetail',
  },
  {
    id: 'log-004',
    cat: 'symptoms',
    dateGroup: 'March 2026',
    ico: '\uD83E\uDE79',
    icoBg: '#FCEBEB',
    title: 'Symptom Log',
    sub: 'Fatigue 8x · tingling 5x · headache 3x',
    pillLabel: '16 entries',
    pillStyle: 'pa',
    meta: 'March 2026',
    date: '2026-03-31',
    symptomTrack: [
      // 31 days – color per day (green = good, amber = mild, red = bad, grey = no entry)
      '#34C759','#34C759','#FF9500','#34C759','#EF5350',
      '#FF9500','#34C759','#B0B0B0','#34C759','#FF9500',
      '#EF5350','#34C759','#FF9500','#34C759','#34C759',
      '#EF5350','#FF9500','#34C759','#34C759','#B0B0B0',
      '#34C759','#FF9500','#EF5350','#34C759','#34C759',
      '#FF9500','#34C759','#EF5350','#34C759','#34C759',
      '#FF9500',
    ],
    footerTags: [
      { label: 'Fatigue 8x', style: 'pr' },
      { label: 'Tingling 5x', style: 'pa' },
      { label: 'Headache 3x', style: 'pa' },
    ],
    detailRoute: 'SymptomLogDetail',
  },
  {
    id: 'log-005',
    cat: 'lifestyle',
    dateGroup: 'February 2026',
    ico: '\uD83D\uDCCA',
    icoBg: '#E1F5EE',
    title: 'Monthly Lifestyle Snapshot',
    sub: 'Sleep · steps · medication tracking',
    pillLabel: 'February 2026',
    pillStyle: 'pg',
    meta: '28 days tracked',
    date: '2026-02-28',
    habitGrid: {
      sleep:      { avg: '5.9h', target: '7.5h', pct: 79, trend: 'down', color: '#5B8DEF' },
      steps:      { avg: '8,240', target: '8,000', pct: 103, trend: 'up', color: '#34C759' },
      medication: { avg: '71%',  target: '100%', pct: 71, trend: 'down', color: '#AF52DE' },
      food:       { avg: '65%',  target: '85%',  pct: 76, trend: 'down', color: '#FF9500' },
    },
    footerTags: [
      { label: 'Sleep 5.9h', style: 'pr' },
      { label: 'Steps 8,240', style: 'pg' },
      { label: 'Meds 71%', style: 'pa' },
    ],
    detailRoute: 'LifestyleSnapshotDetail',
  },
  {
    id: 'log-006',
    cat: 'weight',
    dateGroup: 'March 2026',
    ico: '\u2696\uFE0F',
    icoBg: '#E1F5EE',
    title: 'Weight & BMI',
    sub: '68 kg · BMI 25.0 · down 1.2 kg from last month',
    pillLabel: 'Overweight',
    pillStyle: 'pa',
    meta: 'March 2026 · 8 weigh-ins',
    date: '2026-03-31',
    values: [
      { label: '68 kg', style: 'pa' },
      { label: 'BMI 25.0', style: 'pa' },
      { label: '\u25BC 1.2 kg', style: 'pg' },
    ],
    footerTags: [
      { label: 'Weight', style: 'pa' },
      { label: 'BMI 25', style: 'pa' },
      { label: 'Trending down', style: 'pg' },
    ],
    detailRoute: 'WeightLogDetail',
  },
  {
    id: 'log-007',
    cat: 'mood',
    dateGroup: 'March 2026',
    ico: '\uD83D\uDE0C',
    icoBg: '#EEEDFE',
    title: 'Mood & Stress Log',
    sub: 'Avg mood 6.4/10 · stress moderate',
    pillLabel: 'Moderate',
    pillStyle: 'pa',
    meta: 'March 2026 · 26 entries',
    date: '2026-03-31',
    values: [
      { label: 'Mood 6.4/10', style: 'pa' },
      { label: 'Stress 5.8/10', style: 'pa' },
      { label: 'Best day: 8.5', style: 'pg' },
      { label: 'Low day: 3.2', style: 'pr' },
    ],
    footerTags: [
      { label: 'Mood', style: 'pp' },
      { label: 'Stress', style: 'pa' },
      { label: '26 entries', style: 'pb' },
    ],
    detailRoute: 'MoodLogDetail',
  },
];

// ─── 6. GADGETS ─────────────────────────────────────────────────
const GADGETS = [
  {
    id: 'gad-001',
    title: 'MacBook Pro 14" M3 Pro',
    brand: 'Apple',
    serial: 'C02ZN1ABCDEF',
    price: '\u20B92,14,900',
    purchaseDate: '2024-11-15',
    warrantyDays: 730,
    warrantyTotal: 730,
    warrantyExpiry: '2026-11-15',
    status: 'active',
  },
  {
    id: 'gad-002',
    title: 'iPhone 15 Pro Max 256 GB',
    brand: 'Apple',
    serial: 'DNQXYZ789012',
    price: '\u20B91,34,900',
    purchaseDate: '2025-04-20',
    warrantyDays: 166,
    warrantyTotal: 365,
    warrantyExpiry: '2026-04-20',
    status: 'active',
  },
  {
    id: 'gad-003',
    title: 'Apple Watch Ultra 2 (49 mm)',
    brand: 'Apple',
    serial: 'GHNM45678901',
    price: '\u20B989,900',
    purchaseDate: '2025-05-01',
    warrantyDays: 28,
    warrantyTotal: 365,
    warrantyExpiry: '2026-05-01',
    status: 'expiring',
  },
  {
    id: 'gad-004',
    title: 'Sony WH-1000XM5 Headphones',
    brand: 'Sony',
    serial: 'SN-WH1000XM5-IN42',
    price: '\u20B929,990',
    purchaseDate: '2025-05-15',
    warrantyDays: 45,
    warrantyTotal: 365,
    warrantyExpiry: '2026-05-15',
    status: 'expiring',
  },
  {
    id: 'gad-005',
    title: 'Samsung 65" QN90C Neo QLED',
    brand: 'Samsung',
    serial: 'SAM-QN90C-65-IN7821',
    price: '\u20B91,74,990',
    purchaseDate: '2025-06-10',
    warrantyDays: 591,
    warrantyTotal: 730,
    warrantyExpiry: '2027-06-10',
    status: 'active',
  },
];

// ─── 7. INSURANCE RECORDS ───────────────────────────────────────
const INSURANCE_RECORDS = {
  policy: {
    provider: 'Star Health Insurance',
    planName: 'Family Health Optima',
    type: 'Family Floater',
    policyNumber: 'SH-FHO-2025-IN-483726',
    sumInsured: '\u20B910,00,000',
    sumInsuredRaw: 1000000,
    annualPremium: 18500,
    annualPremiumFormatted: '\u20B918,500',
    members: 4,
    memberNames: ['Ravi Kumar (Self)', 'Priya Kumar (Spouse)', 'Arjun Kumar (Son)', 'Ananya Kumar (Daughter)'],
    validFrom: '2025-08-01',
    validTo: '2026-07-31',
    renewalDue: '2026-07-31',
    networkHospitals: 14000,
    utilised: 9100,
    utilisedFormatted: '\u20B99,100',
    remainingCover: '\u20B99,90,900',
    roomRentLimit: '\u20B95,000/day',
    coPayment: '0%',
    waitingPeriod: '30 days (initial)',
    preExistingWaiting: '3 years',
    tpa: 'Medi Assist',
    policyDoc: 'star-health-fho-483726.pdf',
  },
  claims: [
    {
      id: 'clm-001',
      hospital: 'Apollo Hospital',
      type: 'Cashless',
      amount: 3400,
      amountFormatted: '\u20B93,400',
      date: '2026-03-12',
      status: 'in-review',
      statusLabel: 'In Review',
      description: 'Lab tests – diabetes panel & lipid profile',
      claimNumber: 'CLM-2026-03-0012',
      documents: ['lab-bill-apollo.pdf', 'prescription-meera.pdf'],
      expectedSettlement: '2026-04-05',
    },
    {
      id: 'clm-002',
      hospital: 'Yashoda Hospital',
      type: 'Cashless',
      amount: 8200,
      amountFormatted: '\u20B98,200',
      date: '2025-12-04',
      status: 'settled',
      statusLabel: 'Settled',
      description: 'Cardiac evaluation – 2D Echo + chest X-ray + consultation',
      claimNumber: 'CLM-2025-12-0089',
      documents: ['echo-report.pdf', 'xray-report.pdf', 'hosp-bill.pdf'],
      settledDate: '2025-12-22',
      settledAmount: 8200,
    },
    {
      id: 'clm-003',
      hospital: 'Dr. K. Rajan Clinic',
      type: 'Reimbursement',
      amount: 900,
      amountFormatted: '\u20B9900',
      date: '2026-01-17',
      status: 'settled',
      statusLabel: 'Settled',
      description: 'Cardiologist consultation – annual check-up',
      claimNumber: 'CLM-2026-01-0034',
      documents: ['consultation-receipt.pdf'],
      settledDate: '2026-02-03',
      settledAmount: 900,
    },
  ],
  premiums: [
    {
      id: 'prm-001',
      period: '2025-26',
      amount: 14200,
      amountFormatted: '\u20B914,200',
      paidDate: '2025-07-25',
      mode: 'Annual',
      method: 'UPI – Google Pay',
      receiptNo: 'RCT-SH-2025-07-4821',
      gst: 2556,
      gstFormatted: '\u20B92,556',
      totalPaid: 16756,
      totalPaidFormatted: '\u20B916,756',
    },
  ],
  taxDeduction: {
    eligible: 7200,
    eligibleFormatted: '\u20B97,200',
    saving: 2160,
    savingFormatted: '\u20B92,160',
    slab: '30%',
    section: '80D',
    fy: '2025-26',
    maxLimit: 25000,
    maxLimitFormatted: '\u20B925,000',
  },
};

// ─── EXPORTS ────────────────────────────────────────────────────
module.exports = {
  MAIN_TABS,
  RIBBON_FILTERS,
  STATS_HEADER,
  MEDICAL_RECORDS,
  HEALTH_LOGS,
  GADGETS,
  INSURANCE_RECORDS,
};
