const REFERRAL_TABS = [
  { key: 'ref', label: 'Referrals' },
  { key: 'rewards', label: 'Redeem' },
  { key: 'billing', label: 'Billing' },
  { key: 'history', label: 'History' },
];

const REFERRALS = [
  {
    id: 'ref-001',
    name: 'Ananya Sharma',
    ico: '\uD83D\uDC69\u200D\u2695\uFE0F',
    status: 'active',
    plan: 'Pro Annual',
    planColor: '#34d399',
    joined: '2026-01-14',
    milestone: 'Completed 90-day streak',
    earnings: 120,
  },
  {
    id: 'ref-002',
    name: 'Rohan Mehta',
    ico: '\uD83E\uDDD1\u200D\uD83D\uDCBB',
    status: 'active',
    plan: 'Pro Monthly',
    planColor: '#60a5fa',
    joined: '2026-02-03',
    milestone: 'Logged 50 health readings',
    earnings: 80,
  },
  {
    id: 'ref-003',
    name: 'Priya Nair',
    ico: '\uD83E\uDDD8\u200D\u2640\uFE0F',
    status: 'signed-up',
    plan: 'Basic',
    planColor: '#a1a1aa',
    joined: '2026-03-10',
    milestone: 'Signed up via your link',
    earnings: 25,
  },
  {
    id: 'ref-004',
    name: 'Vikram Desai',
    ico: '\uD83C\uDFCB\uFE0F\u200D\u2642\uFE0F',
    status: 'pending',
    plan: 'Pro Monthly',
    planColor: '#60a5fa',
    joined: '2026-03-21',
    milestone: 'Invite sent, awaiting sign-up',
    earnings: 0,
  },
  {
    id: 'ref-005',
    name: 'Kavitha Rao',
    ico: '\uD83D\uDC69\u200D\uD83D\uDD2C',
    status: 'active',
    plan: 'Family',
    planColor: '#c084fc',
    joined: '2025-11-28',
    milestone: 'Referred 2 more users',
    earnings: 200,
  },
];

const REWARDS_LIST = [
  {
    id: 'rw-001',
    ico: '\uD83D\uDC8E',
    name: '1 Month Pro Upgrade',
    desc: 'Unlock all Pro features for 30 days including advanced health insights.',
    cost: 300,
    col: '#8b5cf6',
    cat: 'subscription',
  },
  {
    id: 'rw-002',
    ico: '\uD83E\uDDEC',
    name: 'DNA Health Report',
    desc: 'Get a personalized genetic wellness report with actionable recommendations.',
    cost: 500,
    col: '#06b6d4',
    cat: 'feature',
  },
  {
    id: 'rw-003',
    ico: '\uD83C\uDF81',
    name: 'Wellness Gift Box',
    desc: 'Curated box with supplements, resistance band, and a guided journal.',
    cost: 750,
    col: '#f43f5e',
    cat: 'gift',
  },
  {
    id: 'rw-004',
    ico: '\uD83D\uDCB0',
    name: '\u20B9200 Cashback',
    desc: 'Redeem coins as cashback credited directly to your linked wallet.',
    cost: 200,
    col: '#22c55e',
    cat: 'cashout',
  },
  {
    id: 'rw-005',
    ico: '\uD83E\uDE7A',
    name: 'Priority Doctor Consult',
    desc: 'Skip the queue and get a same-day video consultation with a specialist.',
    cost: 400,
    col: '#3b82f6',
    cat: 'feature',
  },
  {
    id: 'rw-006',
    ico: '\uD83C\uDFC5',
    name: 'Annual Pro Discount',
    desc: 'Flat 40% off on your next Pro Annual subscription renewal.',
    cost: 600,
    col: '#f59e0b',
    cat: 'subscription',
  },
  {
    id: 'rw-007',
    ico: '\uD83C\uDF3F',
    name: 'Ayurveda Starter Kit',
    desc: 'Herbal tea sampler, tongue scraper, and a dosha guide booklet.',
    cost: 350,
    col: '#10b981',
    cat: 'gift',
  },
  {
    id: 'rw-008',
    ico: '\uD83D\uDCB8',
    name: '\u20B9500 Cashback',
    desc: 'Higher-value cashback for power referrers, credited within 48 hours.',
    cost: 450,
    col: '#14b8a6',
    cat: 'cashout',
  },
];

const REWARD_CATEGORIES = [
  { key: 'subscription', label: 'Subscription' },
  { key: 'feature', label: 'Feature' },
  { key: 'gift', label: 'Gift' },
  { key: 'cashout', label: 'Cashout' },
];

const TIERS = [
  {
    key: 'bronze',
    label: 'Bronze',
    min: 0,
    col: '#b87333',
    perks: [
      'Earn 25 coins per referral sign-up',
      'Access to basic reward catalog',
      'Monthly referral leaderboard badge',
    ],
  },
  {
    key: 'silver',
    label: 'Silver',
    min: 5,
    col: '#9aabb5',
    perks: [
      'Earn 40 coins per referral sign-up',
      'Priority customer support',
      'Exclusive Silver-tier wellness tips',
      '5% discount on lab bookings',
    ],
  },
  {
    key: 'gold',
    label: 'Gold',
    min: 10,
    col: '#f0b429',
    perks: [
      'Earn 60 coins per referral sign-up',
      'Free monthly doctor consultation',
      'Early access to new app features',
      '10% discount on lab bookings',
      'Gold badge on community profile',
    ],
  },
  {
    key: 'platinum',
    label: 'Platinum',
    min: 25,
    col: '#93c5fd',
    perks: [
      'Earn 85 coins per referral sign-up',
      'Dedicated health advisor',
      '20% discount on all services',
      'Free quarterly health check-up',
      'Platinum badge and leaderboard spotlight',
      'Invite-only wellness webinars',
    ],
  },
  {
    key: 'diamond',
    label: 'Diamond',
    min: 50,
    col: '#e0f2fe',
    perks: [
      'Earn 120 coins per referral sign-up',
      'Complimentary Pro Annual subscription',
      'Free unlimited doctor consultations',
      '30% discount on all services',
      'Diamond badge and featured referrer profile',
      'VIP access to health retreats and events',
      'Custom wellness plan by certified expert',
    ],
  },
];

const COIN_HISTORY = [
  {
    ico: '\uD83C\uDF89',
    col: '#22c55e',
    label: 'Referral Bonus',
    desc: 'Ananya Sharma upgraded to Pro Annual',
    amt: '+60',
    date: '2026-03-24',
  },
  {
    ico: '\uD83C\uDF81',
    col: '#f43f5e',
    label: 'Reward Redeemed',
    desc: 'Wellness Gift Box',
    amt: '-750',
    date: '2026-03-20',
  },
  {
    ico: '\uD83D\uDC64',
    col: '#3b82f6',
    label: 'Sign-up Credit',
    desc: 'Priya Nair joined via your referral link',
    amt: '+25',
    date: '2026-03-10',
  },
  {
    ico: '\uD83C\uDFC6',
    col: '#f59e0b',
    label: 'Milestone Reward',
    desc: 'Reached Silver tier with 5 referrals',
    amt: '+100',
    date: '2026-02-28',
  },
  {
    ico: '\uD83D\uDCB0',
    col: '#14b8a6',
    label: 'Cashback Redeemed',
    desc: '\u20B9200 credited to wallet',
    amt: '-200',
    date: '2026-02-15',
  },
  {
    ico: '\uD83D\uDC64',
    col: '#3b82f6',
    label: 'Sign-up Credit',
    desc: 'Rohan Mehta joined via your referral link',
    amt: '+25',
    date: '2026-02-03',
  },
  {
    ico: '\uD83C\uDF1F',
    col: '#a855f7',
    label: 'Welcome Bonus',
    desc: 'Joined the TrustLife Referral Program',
    amt: '+50',
    date: '2026-01-01',
  },
];

const BILLING_PLANS = [
  {
    key: 'basic',
    name: 'Basic',
    price: 'Free',
    tag: null,
    features: [
      'Track up to 5 health metrics',
      'Weekly health summary',
      'Community forum access',
      'Basic symptom logger',
    ],
  },
  {
    key: 'pro',
    name: 'Pro',
    price: '\u20B9299/mo',
    tag: 'current',
    features: [
      'Unlimited health metric tracking',
      'Daily AI-powered health insights',
      'Priority doctor consultations',
      'Advanced symptom analysis',
      'Export health reports as PDF',
      'Ad-free experience',
    ],
  },
  {
    key: 'pro-annual',
    name: 'Pro Annual',
    price: '\u20B92,390/yr',
    tag: 'best value',
    features: [
      'Everything in Pro Monthly',
      'Save 33% compared to monthly',
      'Free annual full-body check-up',
      'Personalized Ayurveda wellness plan',
      'Priority feature requests',
      'Exclusive health webinars',
    ],
  },
  {
    key: 'family',
    name: 'Family',
    price: '\u20B9499/mo',
    tag: 'new',
    features: [
      'Up to 5 family member profiles',
      'Shared family health dashboard',
      'All Pro features for every member',
      'Family doctor consultation slots',
      'Medication reminders for all members',
      'Elder care monitoring tools',
    ],
  },
];

const SHARE_OPTIONS = [
  { key: 'whatsapp', ico: '\uD83D\uDCAC', label: 'WhatsApp' },
  { key: 'sms', ico: '\uD83D\uDCF1', label: 'SMS' },
  { key: 'email', ico: '\uD83D\uDCE7', label: 'Email' },
  { key: 'copy', ico: '\uD83D\uDD17', label: 'Copy Link' },
  { key: 'qr', ico: '\uD83D\uDCF7', label: 'QR Code' },
];

module.exports = {
  REFERRAL_TABS,
  REFERRALS,
  REWARDS_LIST,
  REWARD_CATEGORIES,
  TIERS,
  COIN_HISTORY,
  BILLING_PLANS,
  SHARE_OPTIONS,
};
