const STATS_SUMMARY = {
  totalSpent: 38470,
  totalInvoices: 18,
  claimsFiled: 3,
  claimsAmount: 12400,
  thisMonth: 4180,
  thisMonthCount: 5,
};

const SERVICE_TABS = [
  { key: 'all', label: 'All' },
  { key: 'lab', label: 'Lab', ico: '🧪' },
  { key: 'doc', label: 'Doctor', ico: '👩‍⚕️' },
  { key: 'med', label: 'Medicines', ico: '💊' },
  { key: 'tele', label: 'Telemedicine', ico: '📷' },
  { key: 'coach', label: 'Coach', ico: '🏋' },
  { key: 'couns', label: 'Counselling', ico: '🤝' },
  { key: 'nurse', label: 'Nurse', ico: '👨‍⚕️' },
  { key: 'physio', label: 'Physiotherapy', ico: '🦿' },
  { key: 'hosp', label: 'Hospital', ico: '🏥' },
  { key: 'well', label: 'Wellness', ico: '🌿' },
  { key: 'ins', label: 'Insurance', ico: '🛡️' },
];

const PENDING_CLAIM = {
  title: '1 claim in progress',
  amount: 8200,
  desc: 'Apollo Diagnostics invoice (₹3,400) submitted to Star Health on 18 Mar 2026. Awaiting approval.',
  invId: 'apollo-lab',
};

const SERVICE_INVOICES = [
  // ── Lab (2) ──
  {
    id: 'apollo-lab',
    cat: 'lab',
    type: 'Diagnostic lab',
    name: 'Diabetes Monitoring Panel',
    provider: 'Apollo Diagnostics',
    date: '12 Mar 2026',
    amount: 3400,
    ref: 'INV-APL-2026-0312',
    paymentMethod: 'UPI – Google Pay',
    status: 'claimed',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Claim filed', bg: '#E6F1FB', color: '#1565c0' },
    ],
    items: [
      ['HbA1c test', '₹649'],
      ['Lipid Panel', '₹749'],
      ['Fasting glucose', '₹199'],
      ['Kidney function (KFT)', '₹599'],
      ['Liver function (LFT)', '₹599'],
      ['CBC', '₹349'],
    ],
    gst: 0,
    docs: ['Apollo_DiabetesPanel_12Mar2026.pdf', 'Lab_report_summary.pdf'],
    ayuNote:
      'Your HbA1c has improved from 7.8 to 7.1 over the last quarter — keep the current medication and diet plan going. Lipid ratios look stable.',
    claimStatus: 'filed',
    claimNote: 'Submitted to Star Health on 18 Mar 2026. Awaiting approval.',
    insurer: 'Star Health',
    claimAmount: 3400,
    visitId: 'VIS-2026-03-001',
    linked: ['meera-followup', 'apollo-pharm-mar'],
    icd: 'Z13.1 — Screening for diabetes mellitus',
    diagnosis: 'T2DM monitoring — HbA1c, FBG, Lipid panel, Kidney function',
    doctorRef: 'Dr. Meera Mehta MBBS MD DM',
    rxRef: 'RX-YSH-2026-030572',
  },
  {
    id: 'thyrocare-full',
    cat: 'lab',
    type: 'Diagnostic lab',
    name: 'Aarogyam 1 Full Body Checkup',
    provider: 'Thyrocare',
    date: '8 Jan 2026',
    amount: 999,
    ref: 'INV-THY-2026-0108',
    paymentMethod: 'Debit card – HDFC',
    status: 'paid',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Reports in vault', bg: '#E1F5EE', color: '#0a5c47' },
    ],
    items: [
      ['Complete Blood Count', '₹299'],
      ['Thyroid Profile (T3/T4/TSH)', '₹350'],
      ['Vitamin D', '₹350'],
    ],
    gst: 0,
    docs: ['Thyrocare_Aarogyam1_08Jan2026.pdf'],
    ayuNote:
      'Vitamin D at 18 ng/mL is below optimal. Consider 60K IU weekly supplementation for 8 weeks and retest. Thyroid markers within normal range.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-01-003',
    linked: [],
    icd: 'Z00.00 — Routine general health check',
    diagnosis: 'Annual wellness panel — 76 tests',
    doctorRef: 'Self-referred (preventive)',
    rxRef: null,
  },

  // ── Doctor (2) ──
  {
    id: 'meera-followup',
    cat: 'doc',
    type: 'Doctor consultation',
    name: 'Dr. Meera Mehta Follow-up',
    provider: 'Yashoda Hospital',
    date: '5 Mar 2026',
    amount: 600,
    ref: 'INV-YSH-2026-0305',
    paymentMethod: 'UPI – PhonePe',
    status: 'paid',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Notes synced', bg: '#EEEDFE', color: '#6C63FF' },
    ],
    items: [['Follow-up consultation (Endocrinology)', '₹600']],
    gst: 0,
    docs: ['DrMeera_Followup_05Mar2026.pdf'],
    ayuNote:
      'Dr. Mehta noted steady glucose control. Metformin dose maintained at 500 mg twice daily. Next follow-up in 3 months with fresh HbA1c.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-03-001',
    linked: ['apollo-lab', 'apollo-pharm-mar'],
    icd: 'E11.9 — Type 2 diabetes mellitus',
    diagnosis: 'T2DM follow-up — medication review, HbA1c discussion',
    doctorRef: 'Dr. Meera Mehta MBBS MD DM MCI Reg 2009/01847',
    rxRef: 'RX-YSH-2026-030572',
  },
  {
    id: 'rajan-consult',
    cat: 'doc',
    type: 'Doctor consultation',
    name: 'Dr. K. Rajan First Consult',
    provider: 'Apollo Hospitals',
    date: '17 Jan 2026',
    amount: 900,
    ref: 'INV-APH-2026-0117',
    paymentMethod: 'Credit card – ICICI',
    status: 'settled',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Claim settled', bg: '#E1F5EE', color: '#0a5c47' },
    ],
    items: [['First consultation (General Medicine)', '₹900']],
    gst: 0,
    docs: ['DrRajan_Consult_17Jan2026.pdf'],
    ayuNote:
      'Initial assessment recommended full metabolic panel and thyroid screening. Lifestyle modifications discussed — 30-minute daily walk and reduced sugar intake.',
    claimStatus: 'settled',
    claimNote: 'Settled by Star Health on 28 Jan 2026. ₹900 reimbursed.',
    insurer: 'Star Health',
    claimAmount: 900,
    visitId: 'VIS-2026-01-002',
    linked: [],
    icd: 'I10 — Essential hypertension',
    diagnosis: 'Hypertension first consult — medication review',
    doctorRef: 'Dr. K. Rajan MBBS MD DM Cardiology',
    rxRef: 'RX-APL-2026-010887',
  },

  // ── Telemedicine (1) ──
  {
    id: 'tele-gp-jan',
    cat: 'tele',
    type: 'Telemedicine',
    name: 'Video Consult – General Physician',
    provider: 'TrustLife Telemedicine',
    date: '3 Jan 2026',
    amount: 199,
    ref: 'INV-TLT-2026-0103',
    paymentMethod: 'UPI – Google Pay',
    status: 'paid',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Prescription attached', bg: '#EEEDFE', color: '#6C63FF' },
    ],
    items: [['Video consultation (15 min)', '₹199']],
    gst: 0,
    docs: ['TeleConsult_GP_03Jan2026.pdf', 'Prescription_03Jan2026.pdf'],
    ayuNote:
      'Mild seasonal cold symptoms addressed. Prescribed antihistamine for 5 days and steam inhalation. No antibiotics needed.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-01-001',
    linked: ['medplus-feb'],
    icd: 'J06.9 — Upper respiratory infection',
    diagnosis: 'Acute fever and upper respiratory tract infection',
    doctorRef: 'Dr. Vikram Sinha MBBS',
    rxRef: 'ERXP-TLM-2026-000041',
  },

  // ── Medicines (2) ──
  {
    id: 'apollo-pharm-mar',
    cat: 'med',
    type: 'Pharmacy',
    name: 'Monthly Prescription Refill',
    provider: 'Apollo Pharmacy',
    date: '1 Mar 2026',
    amount: 339,
    ref: 'INV-APR-2026-0301',
    paymentMethod: 'UPI – PhonePe',
    status: 'paid',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Delivered', bg: '#E6F1FB', color: '#1565c0' },
    ],
    items: [
      ['Metformin 500 mg x60', '₹112'],
      ['Telmisartan 40 mg x30', '₹98'],
      ['Atorvastatin 10 mg x30', '₹85'],
      ['Vitamin D3 60K x4', '₹44'],
    ],
    gst: 0,
    docs: ['ApolloPharmacy_Bill_01Mar2026.pdf'],
    ayuNote:
      'All four medications refilled on schedule. Next refill due around 1 Apr 2026. Ayu will remind you 3 days before.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-03-001',
    linked: ['meera-followup', 'apollo-lab'],
    icd: 'E11.9 / I10 / E78.5',
    diagnosis: 'Metformin, Amlodipine, Atorvastatin, Methylcobalamin',
    doctorRef: 'Dr. Meera Mehta',
    rxRef: 'RX-YSH-2026-030572',
  },
  {
    id: 'medplus-feb',
    cat: 'med',
    type: 'Pharmacy',
    name: 'Monthly Prescription Refill',
    provider: 'MedPlus',
    date: '1 Feb 2026',
    amount: 339,
    ref: 'INV-MPL-2026-0201',
    paymentMethod: 'UPI – Google Pay',
    status: 'paid',
    tags: [{ label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' }],
    items: [
      ['Metformin 500 mg x60', '₹112'],
      ['Telmisartan 40 mg x30', '₹98'],
      ['Atorvastatin 10 mg x30', '₹85'],
      ['Vitamin D3 60K x4', '₹44'],
    ],
    gst: 0,
    docs: ['MedPlus_Bill_01Feb2026.pdf'],
    ayuNote:
      'Same prescription as previous month. Consistent refill pattern is great for adherence tracking.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-01-001',
    linked: ['tele-gp-jan'],
    icd: 'E11.9 / I10 / E78.5',
    diagnosis: 'Monthly refill',
    doctorRef: 'Dr. Meera Mehta',
    rxRef: 'RX-YSH-2026-020089',
  },

  // ── Physio (1) ──
  {
    id: 'physio-suresh',
    cat: 'physio',
    type: 'Physiotherapy',
    name: 'Home Session x3 – Suresh Rao',
    provider: 'Home visit',
    date: '14 Mar 2026',
    amount: 2100,
    ref: 'INV-PHY-2026-0314',
    paymentMethod: 'Cash',
    status: 'paid',
    tags: [{ label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' }],
    items: [
      ['Session 1 – lower back assessment', '₹700'],
      ['Session 2 – core strengthening', '₹700'],
      ['Session 3 – flexibility & posture', '₹700'],
    ],
    gst: 0,
    docs: ['PhysioSuresh_Sessions_Mar2026.pdf'],
    ayuNote:
      'Three sessions completed targeting lower back stiffness. Suresh recommends continuing daily stretching routine for 15 minutes. Pain score reduced from 6/10 to 3/10.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-03-002',
    linked: [],
    icd: 'G63.2 — Diabetic polyneuropathy',
    diagnosis: 'Lower limb mobility rehabilitation — 3 sessions',
    doctorRef: 'Suresh Rao BPT',
    rxRef: 'RX-YSH-2026-030572',
  },

  // ── Coach (1) ──
  {
    id: 'coach-priya',
    cat: 'coach',
    type: 'Health coach',
    name: 'Diabetes Nutrition Plan – Month 2',
    provider: 'Priya Talwar, RD',
    date: '10 Feb 2026',
    amount: 450,
    ref: 'INV-COA-2026-0210',
    paymentMethod: 'UPI – Google Pay',
    status: 'paid',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Meal plan attached', bg: '#EEEDFE', color: '#6C63FF' },
    ],
    items: [['Nutrition consultation + custom meal plan (Month 2)', '₹450']],
    gst: 0,
    docs: ['PriyaTalwar_MealPlan_Feb2026.pdf'],
    ayuNote:
      'Month 2 meal plan introduces more millet-based meals and reduces refined carb portions. Target: bring post-meal glucose spikes under 160 mg/dL.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-02-001',
    linked: [],
    icd: null,
    diagnosis: null,
    doctorRef: null,
    rxRef: null,
  },

  // ── Counselling (1) ──
  {
    id: 'couns-nisha',
    cat: 'couns',
    type: 'Counselling',
    name: 'Stress Management – Session 1',
    provider: 'Nisha Kapoor',
    date: '22 Jan 2026',
    amount: 299,
    ref: 'INV-COU-2026-0122',
    paymentMethod: 'UPI – PhonePe',
    status: 'paid',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Anonymous mode', bg: '#FFF3E0', color: '#e65100' },
    ],
    items: [['Counselling session (45 min)', '₹299']],
    gst: 0,
    docs: [],
    ayuNote:
      'First session focused on identifying stress triggers related to work and health management. Breathing exercises prescribed — 10 min morning and evening.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-01-005',
    linked: [],
    icd: 'F43.1 — Stress reaction',
    diagnosis: 'Adjustment disorder with anxiety',
    doctorRef: 'Nisha Kapoor M.Phil Clinical Psychology',
    rxRef: null,
  },

  // ── Nurse (1) ──
  {
    id: 'nurse-portea',
    cat: 'nurse',
    type: 'Nursing care',
    name: 'Dressing & IV – 2 Visits',
    provider: 'Portea Medical',
    date: '9 Jan 2026',
    amount: 1800,
    ref: 'INV-PRT-2026-0109',
    paymentMethod: 'Credit card – SBI',
    status: 'paid',
    tags: [{ label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' }],
    items: [
      ['Wound dressing (Visit 1)', '₹700'],
      ['IV fluid administration (Visit 1)', '₹400'],
      ['Wound dressing (Visit 2)', '₹700'],
    ],
    gst: 0,
    docs: ['Portea_NursingVisits_Jan2026.pdf'],
    ayuNote:
      'Post-procedure wound care completed in 2 home visits. Healing on track — no signs of infection. Stitches removed during second visit.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-01-004',
    linked: [],
    icd: 'Z48.0 — Encounter for wound care',
    diagnosis: 'Post-procedure dressing and IV — 2 home visits',
    doctorRef: 'Portea Certified Nurse',
    rxRef: null,
  },

  // ── Hospital (1) ──
  {
    id: 'hosp-yashoda-opd',
    cat: 'hosp',
    type: 'Hospital OPD',
    name: 'OPD – Endocrinology Dept',
    provider: 'Yashoda Hospital',
    date: '4 Dec 2025',
    amount: 8200,
    ref: 'INV-YSH-2025-1204',
    paymentMethod: 'Credit card – HDFC',
    status: 'settled',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Claim settled', bg: '#E1F5EE', color: '#0a5c47' },
    ],
    items: [
      ['OPD registration', '₹200'],
      ['Endocrinologist consultation', '₹1,000'],
      ['HbA1c + Lipid Panel', '₹1,400'],
      ['Ultrasound abdomen', '₹2,200'],
      ['ECG', '₹600'],
      ['Dietician consultation', '₹500'],
      ['Pharmacy (medications)', '₹2,300'],
    ],
    gst: 0,
    docs: ['Yashoda_OPD_04Dec2025.pdf', 'Yashoda_DetailedBill_Dec2025.pdf'],
    ayuNote:
      'Comprehensive OPD visit covering diabetes review, cardiac screening, and abdominal ultrasound. All reports normal except mildly elevated LDL — managed with atorvastatin.',
    claimStatus: 'settled',
    claimNote: 'Settled by Star Health on 22 Dec 2025. ₹8,100 reimbursed (₹100 registration excluded).',
    insurer: 'Star Health',
    claimAmount: 8100,
    visitId: 'VIS-2025-12-001',
    linked: [],
    icd: 'E11.9 — Type 2 DM',
    diagnosis: 'OPD visit — endocrinology, diagnostics, ECG, Echo',
    doctorRef: 'Dr. Meera Mehta & Yashoda Endocrinology',
    rxRef: 'RX-YSH-2025-120384',
  },

  // ── Wellness (1) ──
  {
    id: 'well-prakriti',
    cat: 'well',
    type: 'Wellness centre',
    name: 'Panchakarma – 3 Session Package',
    provider: 'Prakriti Wellness',
    date: '20 Feb 2026',
    amount: 3600,
    ref: 'INV-PRK-2026-0220',
    paymentMethod: 'UPI – Google Pay',
    status: 'paid',
    tags: [{ label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' }],
    items: [
      ['Abhyanga massage session', '₹1,200'],
      ['Shirodhara therapy session', '₹1,200'],
      ['Swedana steam therapy session', '₹1,200'],
    ],
    gst: 648,
    docs: ['Prakriti_Panchakarma_Feb2026.pdf'],
    ayuNote:
      'Panchakarma package for stress relief and metabolic balance. Many patients with Type 2 diabetes report improved sleep and reduced stress hormones after regular sessions.',
    claimStatus: 'none',
    claimNote: null,
    insurer: null,
    claimAmount: 0,
    visitId: 'VIS-2026-02-002',
    linked: [],
    icd: null,
    diagnosis: null,
    doctorRef: null,
    rxRef: null,
  },

  // ── Insurance (1) ──
  {
    id: 'ins-star-premium',
    cat: 'ins',
    type: 'Insurance premium',
    name: 'Star Health Comprehensive Family Premium',
    provider: 'Star Health Insurance',
    date: '1 Jan 2026',
    amount: 14200,
    ref: 'INV-STR-2026-0101',
    paymentMethod: 'Auto-debit – HDFC Savings',
    status: 'paid',
    tags: [
      { label: '✓ Paid', bg: '#E1F5EE', color: '#0a5c47' },
      { label: 'Active policy', bg: '#E6F1FB', color: '#1565c0' },
    ],
    items: [
      ['Base premium (Family floater ₹5L)', '₹12,100'],
      ['GST @ 18%', '₹2,100'],
    ],
    gst: 2100,
    docs: ['StarHealth_Premium_2026.pdf', 'Policy_Schedule_2026.pdf'],
    ayuNote:
      'Annual premium paid for 2026. Family floater cover of ₹5,00,000. Policy valid until 31 Dec 2026. You can save up to ₹25,000 under Section 80D.',
    claimStatus: 'none',
    claimNote: null,
    insurer: 'Star Health',
    claimAmount: 0,
    visitId: 'VIS-2026-01-INS',
    linked: [],
    icd: null,
    diagnosis: null,
    doctorRef: null,
    rxRef: null,
  },
];

const ADD_OPTIONS = [
  {
    ico: '📷',
    title: 'Scan bill or receipt',
    sub: 'Camera · Ayu auto-extracts provider, amount, date',
    bg: '#FCEBEB',
  },
  {
    ico: '📄',
    title: 'Upload PDF invoice',
    sub: 'Hospital bill, lab report invoice, pharmacy receipt',
    bg: '#E6F1FB',
  },
  {
    ico: '📧',
    title: 'Import from email',
    sub: 'Gmail · Outlook · Auto-detected health invoices',
    bg: '#E1F5EE',
  },
  {
    ico: '✏️',
    title: 'Enter manually',
    sub: 'Type in invoice details, amount, and provider',
    bg: '#FAEEDA',
  },
];

const VISIT_META = {
  'VIS-2026-03-001': {date: '5 Mar 2026', title: 'Dr. Meera Mehta \u2014 Diabetologist follow-up', note: 'Consultation + prescribed lab tests + medication refill'},
  'VIS-2026-01-001': {date: '3 Jan 2026', title: 'Telemedicine \u2014 General Physician', note: 'Video consult + e-prescription filled in February'},
  'VIS-2026-01-002': {date: '17 Jan 2026', title: 'Dr. K. Rajan \u2014 Cardiologist, first visit', note: 'Standalone consultation'},
  'VIS-2026-01-003': {date: '8 Jan 2026', title: 'Thyrocare \u2014 Full body panel', note: 'Standalone preventive lab test'},
  'VIS-2026-01-004': {date: '9 Jan 2026', title: 'Home nursing \u2014 Portea Medical', note: 'Post-procedure nursing visits'},
  'VIS-2026-01-005': {date: '22 Jan 2026', title: 'Counselling \u2014 Nisha Kapoor', note: 'Stress management session'},
  'VIS-2026-01-INS': {date: '1 Jan 2026', title: 'Insurance premium \u2014 Star Health', note: 'Annual policy renewal'},
  'VIS-2026-02-001': {date: '10 Feb 2026', title: 'Dietitian session \u2014 Priya Talwar', note: 'Standalone coaching session'},
  'VIS-2026-02-002': {date: '20 Feb 2026', title: 'Panchakarma \u2014 Prakriti Wellness', note: 'Standalone wellness package'},
  'VIS-2026-03-002': {date: '14 Mar 2026', title: 'Physiotherapy \u00D73 \u2014 Suresh Rao', note: 'Home visit package'},
  'VIS-2025-12-001': {date: '4 Dec 2025', title: 'Yashoda Hospitals \u2014 OPD, Endocrinology', note: 'Hospital OPD visit'},
};

const POLICY_INFO = {
  company: 'Star Health and Allied Insurance Co. Ltd.',
  policyNo: 'P/211121/01/2026/008841',
  holder: 'Priya Reddy',
  dob: '14 Sep 1987',
  idProof: 'Aadhaar XXXX XXXX 4821',
  address: 'Flat 4B, Green Valley Apts, Road No. 12, Banjara Hills, Hyderabad 500034',
  email: 'priya@email.com',
  phone: '+91 98480 12345',
  bank: 'HDFC Bank A/c XXXX6481 IFSC HDFC0001234',
};

const INELIGIBLE_CATS = ['coach', 'well', 'ins'];

module.exports = {
  STATS_SUMMARY,
  SERVICE_TABS,
  PENDING_CLAIM,
  SERVICE_INVOICES,
  ADD_OPTIONS,
  VISIT_META,
  POLICY_INFO,
  INELIGIBLE_CATS,
};
