import React, {useState, useEffect, useRef, useCallback} from 'react';
import {View, StyleSheet, TouchableOpacity, StatusBar, ScrollView, TextInput, Alert} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {useNavigation} from '@react-navigation/native';
import {scale as s, verticalScale as vs, moderateScale as ms} from 'react-native-size-matters';
import Colors from '../../constants/colors';
import AppText from '../../components/shared/AppText';
import Icon from '../../components/shared/Icons';

const TERMS_TEXT = [
  {heading: 'PRIMARY MEDICAL DISCLAIMER', red: true, body: 'TrustLife is NOT a medical device and does NOT provide medical advice, diagnosis, or treatment. All health insights generated by Ayu Intelligence are strictly informational. Always consult a qualified healthcare professional before making any medical decisions. In emergencies, call 112 or visit your nearest hospital immediately.'},
  {heading: '1. Acceptance of Terms', body: 'By creating an account and using TrustLife, you agree to be bound by these Terms of Service, our Privacy Policy, and our Data Processing Agreement. If you do not agree, do not use the service.'},
  {heading: '2. Health Data Processing', body: 'You consent to TrustLife collecting, storing, and processing your health data including medical records, lab reports, medications, vitals, and symptom logs. All data is encrypted with AES-256 and stored on AWS Mumbai servers within India.'},
  {heading: '3. Ayu Intelligence', body: 'Ayu is an AI-powered health analysis engine. It provides trends, scores, and insights based on your health data. Ayu outputs are NOT medical diagnoses. Accuracy depends on data quality and completeness. TrustLife is not liable for decisions made based on Ayu insights.'},
  {heading: '4. Data Ownership & Portability', body: 'You retain full ownership of your health data. You may export your data in FHIR, PDF, or CSV format at any time. You may request complete data deletion at any time, which will be processed within 48 hours.'},
  {heading: '5. Sharing & Consent', body: 'Your data is never shared without explicit consent. Doctor sharing via TrustMD requires your per-session approval. You can revoke any sharing consent at any time from Settings > Privacy.'},
  {heading: '6. Subscription & Billing', body: 'Free tier is available indefinitely. Paid plans are billed monthly or annually. 14-day free trial for new paid subscribers. Cancel anytime; access continues until the end of the billing period. Refunds are processed as per RBI guidelines.'},
  {heading: '7. Limitation of Liability', body: 'TrustLife shall not be liable for any direct, indirect, incidental, or consequential damages arising from use of the service. Maximum liability is limited to the amount paid in the preceding 12 months.'},
];

const TermsScreen = () => {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation();
  const [scrollPct, setScrollPct] = useState(0);
  const [termsRead, setTermsRead] = useState(false);
  const [signatureName, setSignatureName] = useState('');

  const nameValid = signatureName.trim().length >= 3 && signatureName.trim().includes(' ');

  useEffect(() => {
    if (scrollPct >= 88 && !termsRead) {
      setTermsRead(true);
    }
  }, [scrollPct, termsRead]);

  const handleScroll = useCallback((e) => {
    const {contentOffset, contentSize, layoutMeasurement} = e.nativeEvent;
    const maxScroll = contentSize.height - layoutMeasurement.height;
    if (maxScroll > 0) {
      const pct = Math.round((contentOffset.y / maxScroll) * 100);
      setScrollPct(Math.min(pct, 100));
    }
  }, []);

  const handleDecline = useCallback(() => {
    Alert.alert(
      'Decline Terms?',
      'You must accept the Terms of Service to use TrustLife. If you decline, your account setup will not be completed.',
      [
        {text: 'Go back', style: 'cancel'},
        {text: 'Decline', style: 'destructive', onPress: () => navigation.goBack()},
      ],
    );
  }, [navigation]);

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor={Colors.primary} />

      {/* Green header */}
      <View style={[styles.header, {paddingTop: insets.top}]}>
        <View style={styles.topBar}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
            <Icon family="Ionicons" name="chevron-back" size={18} color={Colors.white} />
          </TouchableOpacity>
          <View style={{flex: 1, marginLeft: s(10)}}>
            <AppText variant="screenName" style={styles.headerTitle}>Terms of Service</AppText>
            <AppText variant="caption" style={styles.headerSub}>Read and sign with your name to proceed</AppText>
          </View>
          <AppText variant="small" color="rgba(255,255,255,0.5)">Step 7 {'\u00B7'} Part 1</AppText>
        </View>
      </View>

      {/* Progress */}
      <View style={styles.progressTrack}>
        <View style={[styles.progressFill, {width: '92%'}]} />
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}>

        {/* Scroll progress indicator */}
        <View style={styles.scrollIndicator}>
          <View style={styles.scrollTrack}>
            <View style={[styles.scrollFill, {width: `${scrollPct}%`}]} />
          </View>
          <AppText variant="small" color={Colors.textSecondary} style={styles.scrollPctLabel}>
            {scrollPct}%
          </AppText>
        </View>

        {/* Terms ScrollView */}
        <View style={styles.termsContainer}>
          <ScrollView
            style={styles.termsScroll}
            nestedScrollEnabled
            showsVerticalScrollIndicator
            onScroll={handleScroll}
            scrollEventThrottle={16}>
            {TERMS_TEXT.map((section, i) => (
              <View key={i} style={styles.termsSection}>
                <AppText
                  variant="bodyBold"
                  color={section.red ? Colors.red : Colors.textPrimary}
                  style={styles.termsHeading}>
                  {section.heading}
                </AppText>
                <AppText variant="caption" color={Colors.textSecondary} style={styles.termsParagraph}>
                  {section.body}
                </AppText>
              </View>
            ))}
          </ScrollView>
        </View>

        {/* Signature block (only when terms read) */}
        {termsRead && (
          <View style={styles.signatureCard}>
            <AppText variant="body" color={Colors.tealText} style={styles.consentStatement}>
              I, <AppText variant="bodyBold" color={Colors.tealText}>{signatureName.trim() || '[your name]'}</AppText>, have read and understood the TrustLife Terms of Service and agree to be bound by them.
            </AppText>
            <AppText variant="caption" color={Colors.textSecondary} style={styles.signatureLabel}>
              Type your full name
            </AppText>
            <TextInput
              style={styles.signatureInput}
              placeholder="First Last"
              placeholderTextColor={Colors.textTertiary}
              value={signatureName}
              onChangeText={setSignatureName}
              autoCapitalize="words"
            />
          </View>
        )}

        {/* Download ToS PDF */}
        <TouchableOpacity style={styles.downloadCard} activeOpacity={0.7}>
          <AppText style={styles.downloadIcon}>{'\uD83D\uDCC4'}</AppText>
          <View style={styles.downloadInfo}>
            <AppText variant="bodyBold">Download full Terms of Service</AppText>
            <AppText variant="caption" color={Colors.textSecondary}>PDF {'\u00B7'} 12 pages</AppText>
          </View>
        </TouchableOpacity>
      </ScrollView>

      {/* Bottom bar */}
      <View style={[styles.bottomBar, {paddingBottom: insets.bottom + vs(12)}]}>
        <TouchableOpacity
          style={[styles.ctaBtn, !(termsRead && nameValid) && styles.ctaBtnDisabled]}
          onPress={() => {
            if (termsRead && nameValid) {
              navigation.navigate('Consent');
            }
          }}
          activeOpacity={termsRead && nameValid ? 0.7 : 1}>
          <View style={{flexDirection:"row",alignItems:"center",gap:s(4)}}><AppText variant="bodyBold" color={Colors.white} style={{lineHeight:ms(16)}}>Sign & Accept</AppText><Icon family="Ionicons" name="arrow-forward" size={16} color={Colors.white} /></View>
        </TouchableOpacity>
        <TouchableOpacity onPress={handleDecline} style={styles.declineLink}>
          <AppText variant="caption" color={Colors.red}>Decline</AppText>
        </TouchableOpacity>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: s(20),
    paddingTop: vs(20),
    paddingBottom: vs(20),
  },
  header: {backgroundColor: Colors.primary, paddingBottom: vs(14), paddingHorizontal: s(16)},
  topBar: {flexDirection: 'row', alignItems: 'center', marginBottom: vs(6)},
  backBtn: {
    width: ms(30),
    height: ms(30),
    borderRadius: ms(15),
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: ms(2),
  },
  backIcon: {
    fontSize: ms(24),
    fontWeight: '600',
    marginTop: -vs(2),
  },
  progressTrack: {
    height: vs(4),
    backgroundColor: Colors.borderLight,
    borderRadius: ms(2),
    marginBottom: vs(16),
  },
  progressFill: {
    height: '100%',
    backgroundColor: Colors.accent,
    borderRadius: ms(2),
  },
  headerTitle: {color: Colors.white, fontSize: ms(18), fontWeight: '700'},
  headerSub: {color: 'rgba(255,255,255,0.5)', fontSize: ms(12)},
  title: {
    fontSize: ms(22),
    fontWeight: '800',
    marginBottom: vs(6),
    color: Colors.textPrimary,
  },
  subtitle: {
    marginBottom: vs(12),
  },
  scrollIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: vs(8),
  },
  scrollTrack: {
    flex: 1,
    height: vs(6),
    backgroundColor: Colors.borderLight,
    borderRadius: ms(3),
    overflow: 'hidden',
    marginRight: s(8),
  },
  scrollFill: {
    height: '100%',
    backgroundColor: Colors.accent,
    borderRadius: ms(3),
  },
  scrollPctLabel: {
    width: s(32),
    textAlign: 'right',
  },
  termsContainer: {
    height: vs(220),
    backgroundColor: Colors.white,
    borderRadius: ms(14),
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: vs(12),
    overflow: 'hidden',
  },
  termsScroll: {
    padding: s(12),
  },
  termsSection: {
    marginBottom: vs(12),
  },
  termsHeading: {
    marginBottom: vs(4),
  },
  termsParagraph: {
    lineHeight: ms(18),
  },
  signatureCard: {
    backgroundColor: Colors.tealBg,
    borderRadius: ms(14),
    padding: s(14),
    marginBottom: vs(8),
  },
  consentStatement: {
    marginBottom: vs(10),
    lineHeight: ms(20),
  },
  signatureLabel: {
    marginBottom: vs(4),
  },
  signatureInput: {
    backgroundColor: Colors.white,
    borderRadius: ms(10),
    padding: s(12),
    fontSize: ms(14),
    color: Colors.textPrimary,
  },
  downloadCard: {
    backgroundColor: Colors.white,
    borderRadius: ms(14),
    padding: s(14),
    marginBottom: vs(8),
    flexDirection: 'row',
    alignItems: 'center',
  },
  downloadIcon: {
    fontSize: ms(22),
    marginRight: s(12),
  },
  downloadInfo: {
    flex: 1,
  },
  bottomBar: {
    paddingHorizontal: s(20),
    paddingTop: vs(12),
    backgroundColor: Colors.background,
  },
  ctaBtn: {
    backgroundColor: Colors.primary,
    borderRadius: ms(14),
    paddingVertical: vs(16),
    alignItems: 'center',
  },
  ctaBtnDisabled: {
    opacity: 0.5,
  },
  declineLink: {
    alignItems: 'center',
    marginTop: vs(12),
  },
});

export default TermsScreen;
